import {
  Requisition,
  StockAdjustmentAuditEntry,
  Substore,
  SubstoreItem,
} from "./types";

export const INITIAL_SUBSTORES: Substore[] = [
  {
    id: "ss-001",
    code: "SS-MALE-MED",
    name: "Male Medical Ward Sub-store",
    department: "Internal Medicine",
    wardLocation: "Block B, 2nd Floor, Ward 3",
    managerName: "Staff Nurse Chinedu Okafor",
    managerRole: "WARD_INCHARGE_NURSE",
    contactPhone: "+234 803 123 4567",
  },
  {
    id: "ss-002",
    code: "SS-FEMALE-SURG",
    name: "Female Surgical Ward Sub-store",
    department: "Surgery",
    wardLocation: "Block A, 3rd Floor, Ward 4",
    managerName: "Senior Nursing Officer Maryam Adamu",
    managerRole: "WARD_INCHARGE_NURSE",
    contactPhone: "+234 802 456 7890",
  },
  {
    id: "ss-003",
    code: "SS-THEATRE",
    name: "Main Operating Theatre Sub-store",
    department: "Surgical Services",
    wardLocation: "Surgical Complex, Theatre 1-4 Depot",
    managerName: "Matron Grace Edet",
    managerRole: "THEATRE_SUPERVISOR",
    contactPhone: "+234 805 678 9012",
  },
  {
    id: "ss-004",
    code: "SS-PEDS",
    name: "Paediatrics & Emergency Nursery Sub-store",
    department: "Paediatrics",
    wardLocation: "Maternal & Child Complex, Ward 1",
    managerName: "Nursing Officer Funke Balogun",
    managerRole: "WARD_INCHARGE_NURSE",
    contactPhone: "+234 809 234 5678",
  },
  {
    id: "ss-005",
    code: "SS-A-AND-E",
    name: "Accident & Emergency Rapid Sub-store",
    department: "Emergency Medicine",
    wardLocation: "Ground Floor, A&E Resuscitation Bay",
    managerName: "Chief Nursing Officer Emeka Obi",
    managerRole: "A_AND_E_COORDINATOR",
    contactPhone: "+234 806 345 6789",
  },
];

export const INITIAL_SUBSTORE_ITEMS: SubstoreItem[] = [
  // --- SS-001: Male Medical Ward ---
  {
    id: "item-001",
    substoreId: "ss-001",
    itemCode: "MED-SYR-05ML",
    itemName: "Disposable Syringe with Needle 5ml (Latex Free)",
    category: "CONSUMABLE",
    unitOfMeasure: "Pieces",
    currentStock: 180,
    reorderLevel: 50,
    maxCapacity: 300,
    unitCost: 120,
    lastRestockedAt: "2026-09-24T10:00:00Z",
    status: "IN_STOCK",
  },
  {
    id: "item-002",
    substoreId: "ss-001",
    itemCode: "MED-CAN-20G",
    itemName: "IV Cannula 20G (Pink) with Port & Wings",
    category: "CONSUMABLE",
    unitOfMeasure: "Pieces",
    currentStock: 22,
    reorderLevel: 30, // Low stock trigger
    maxCapacity: 150,
    unitCost: 350,
    lastRestockedAt: "2026-09-20T14:30:00Z",
    status: "LOW_STOCK",
  },
  {
    id: "item-003",
    substoreId: "ss-001",
    itemCode: "MED-NS-500ML",
    itemName: "0.9% Normal Saline IV Infusion 500ml",
    category: "PHARMACEUTICAL",
    unitOfMeasure: "Bottles",
    currentStock: 45,
    reorderLevel: 25,
    maxCapacity: 120,
    unitCost: 850,
    lastRestockedAt: "2026-09-25T08:15:00Z",
    status: "IN_STOCK",
  },
  {
    id: "item-004",
    substoreId: "ss-001",
    itemCode: "MED-GLV-MED",
    itemName: "Examination Gloves (Nitrile Medium) Powder-free",
    category: "CONSUMABLE",
    unitOfMeasure: "Boxes (100s)",
    currentStock: 2,
    reorderLevel: 5, // Low stock trigger
    maxCapacity: 20,
    unitCost: 4500,
    lastRestockedAt: "2026-09-15T11:00:00Z",
    status: "LOW_STOCK",
  },
  {
    id: "item-005",
    substoreId: "ss-001",
    itemCode: "MED-PARA-IV",
    itemName: "Paracetamol IV Infusion 10mg/ml 100ml",
    category: "PHARMACEUTICAL",
    unitOfMeasure: "Vials",
    currentStock: 35,
    reorderLevel: 20,
    maxCapacity: 100,
    unitCost: 1200,
    lastRestockedAt: "2026-09-26T16:00:00Z",
    status: "IN_STOCK",
  },

  // --- SS-002: Female Surgical Ward ---
  {
    id: "item-006",
    substoreId: "ss-002",
    itemCode: "SURG-GLV-7.5",
    itemName: "Sterile Surgical Gloves Size 7.5",
    category: "SURGICAL_SUPPLY",
    unitOfMeasure: "Pairs",
    currentStock: 65,
    reorderLevel: 40,
    maxCapacity: 200,
    unitCost: 650,
    lastRestockedAt: "2026-09-23T12:00:00Z",
    status: "IN_STOCK",
  },
  {
    id: "item-007",
    substoreId: "ss-002",
    itemCode: "SURG-GAU-ROLL",
    itemName: "Sterile Gauze Bandage Roll (10cm x 5m)",
    category: "CONSUMABLE",
    unitOfMeasure: "Rolls",
    currentStock: 8,
    reorderLevel: 20, // Low stock trigger
    maxCapacity: 80,
    unitCost: 400,
    lastRestockedAt: "2026-09-18T09:30:00Z",
    status: "LOW_STOCK",
  },
  {
    id: "item-008",
    substoreId: "ss-002",
    itemCode: "SURG-SUT-VIC2",
    itemName: "Vicryl 2/0 Absorbable Suture with Curved Needle",
    category: "SURGICAL_SUPPLY",
    unitOfMeasure: "Packs",
    currentStock: 14,
    reorderLevel: 15,
    maxCapacity: 60,
    unitCost: 2800,
    lastRestockedAt: "2026-09-22T15:20:00Z",
    status: "LOW_STOCK",
  },

  // --- SS-003: Main Operating Theatre ---
  {
    id: "item-009",
    substoreId: "ss-003",
    itemCode: "TH-BLD-11",
    itemName: "Carbon Steel Surgical Scalpel Blade #11",
    category: "SURGICAL_SUPPLY",
    unitOfMeasure: "Packs (100s)",
    currentStock: 12,
    reorderLevel: 5,
    maxCapacity: 30,
    unitCost: 7500,
    lastRestockedAt: "2026-09-21T10:00:00Z",
    status: "IN_STOCK",
  },
  {
    id: "item-010",
    substoreId: "ss-003",
    itemCode: "TH-DRP-PACK",
    itemName: "Universal Surgical Drape Pack (Laparotomy Sterile)",
    category: "SURGICAL_SUPPLY",
    unitOfMeasure: "Kits",
    currentStock: 18,
    reorderLevel: 10,
    maxCapacity: 40,
    unitCost: 14000,
    lastRestockedAt: "2026-09-24T17:00:00Z",
    status: "IN_STOCK",
  },
];

export const INITIAL_REQUISITIONS: Requisition[] = [
  {
    id: "req-001",
    requisitionNumber: "REQ-2026-0078",
    substoreId: "ss-001",
    substoreName: "Male Medical Ward Sub-store",
    wardLocation: "Block B, Ward 3",
    requestedBy: "Nurse Chinedu Okafor",
    requestedByRole: "WARD_INCHARGE_NURSE",
    requestedAt: "2026-09-27T08:30:00Z",
    urgency: "ROUTINE",
    items: [
      {
        id: "reqi-1",
        itemId: "item-002",
        itemCode: "MED-CAN-20G",
        itemName: "IV Cannula 20G (Pink) with Port & Wings",
        requestedQty: 50,
        approvedQty: 50,
        unitOfMeasure: "Pieces",
        unitCost: 350,
      },
      {
        id: "reqi-2",
        itemId: "item-004",
        itemCode: "MED-GLV-MED",
        itemName: "Examination Gloves (Nitrile Medium) Powder-free",
        requestedQty: 10,
        approvedQty: 10,
        unitOfMeasure: "Boxes (100s)",
        unitCost: 4500,
      },
    ],
    status: "FULFILLED",
    approvedBy: "Alhaji Garba Sani (Store Keeper)",
    approvedAt: "2026-09-27T11:00:00Z",
    fulfilledBy: "Central Store Dispatch Desk",
    fulfilledAt: "2026-09-27T14:30:00Z",
    remarks: "Dispatched from Central Warehouse Bin 4B. Stock received in ward.",
  },
  {
    id: "req-002",
    requisitionNumber: "REQ-2026-0079",
    substoreId: "ss-002",
    substoreName: "Female Surgical Ward Sub-store",
    wardLocation: "Block A, Ward 4",
    requestedBy: "Maryam Adamu",
    requestedByRole: "WARD_INCHARGE_NURSE",
    requestedAt: "2026-09-28T09:15:00Z",
    urgency: "URGENT",
    items: [
      {
        id: "reqi-3",
        itemId: "item-007",
        itemCode: "SURG-GAU-ROLL",
        itemName: "Sterile Gauze Bandage Roll (10cm x 5m)",
        requestedQty: 40,
        unitOfMeasure: "Rolls",
        unitCost: 400,
      },
      {
        id: "reqi-4",
        itemId: "item-008",
        itemCode: "SURG-SUT-VIC2",
        itemName: "Vicryl 2/0 Absorbable Suture with Curved Needle",
        requestedQty: 25,
        unitOfMeasure: "Packs",
        unitCost: 2800,
      },
    ],
    status: "SUBMITTED",
    remarks: "Post-op dressing stock depleted following emergency weekend cases.",
  },
];

export const INITIAL_STOCK_AUDIT_LOGS: StockAdjustmentAuditEntry[] = [
  {
    id: "aud-001",
    substoreId: "ss-001",
    substoreName: "Male Medical Ward Sub-store",
    itemId: "item-001",
    itemCode: "MED-SYR-05ML",
    itemName: "Disposable Syringe with Needle 5ml",
    previousQty: 200,
    newQty: 180,
    differenceQty: -20,
    reason: "DAMAGED",
    auditExplanation: "Water leakage in shelf B container caused seal breach on 20 units. Disposed per infection control.",
    adjustedBy: "Matron Chinedu Okafor",
    adjustedAt: "2026-09-26T14:20:00Z",
  },
  {
    id: "aud-002",
    substoreId: "ss-002",
    substoreName: "Female Surgical Ward Sub-store",
    itemId: "item-006",
    itemCode: "SURG-GLV-7.5",
    itemName: "Sterile Surgical Gloves Size 7.5",
    previousQty: 60,
    newQty: 65,
    differenceQty: 5,
    reason: "PHYSICAL_COUNT_CORRECTION",
    auditExplanation: "Unopened box found during weekly ward inventory reconciliation.",
    adjustedBy: "Maryam Adamu",
    adjustedAt: "2026-09-25T16:00:00Z",
  },
];
