import { Drug, Prescription } from './types';

export const INITIAL_DRUGS: Drug[] = [
  {
    id: 'drg-001',
    genericName: 'Amoxicillin / Clavulanic Acid',
    brandName: 'Augmentin',
    category: 'Antibiotics',
    dosageForm: 'Tablet',
    strength: '625mg',
    unitPrice: 2800,
    stockOnHand: 140,
    reorderLevel: 50,
    batchNumber: 'AUG-2026-B1',
    expiryDate: '2027-08-31',
    activeIngredients: ['Amoxicillin', 'Clavulanate Potassium'],
    contraindications: ['Penicillin Allergy', 'History of Amoxicillin-associated cholestatic jaundice']
  },
  {
    id: 'drg-002',
    genericName: 'Ciprofloxacin',
    brandName: 'Cipro-Denk',
    category: 'Antibiotics',
    dosageForm: 'Tablet',
    strength: '500mg',
    unitPrice: 1200,
    stockOnHand: 85,
    reorderLevel: 40,
    batchNumber: 'CIP-2026-X4',
    expiryDate: '2028-01-15',
    activeIngredients: ['Ciprofloxacin Hydrochloride'],
    contraindications: ['Fluoroquinolone Hypersensitivity', 'Myasthenia Gravis']
  },
  {
    id: 'drg-003',
    genericName: 'Paracetamol',
    brandName: 'Panadol Extra',
    category: 'Analgesics / NSAIDs',
    dosageForm: 'Tablet',
    strength: '500mg',
    unitPrice: 350,
    stockOnHand: 450,
    reorderLevel: 100,
    batchNumber: 'PCM-2026-A9',
    expiryDate: '2028-06-30',
    activeIngredients: ['Paracetamol', 'Caffeine'],
    contraindications: ['Severe Hepatic Impairment']
  },
  {
    id: 'drg-004',
    genericName: 'Ibuprofen',
    brandName: 'Brufen',
    category: 'Analgesics / NSAIDs',
    dosageForm: 'Tablet',
    strength: '400mg',
    unitPrice: 450,
    stockOnHand: 18, // Low Stock trigger
    reorderLevel: 50,
    batchNumber: 'IBU-2025-C2',
    expiryDate: '2026-12-31',
    activeIngredients: ['Ibuprofen'],
    contraindications: ['NSAIDs Allergy', 'Active Peptic Ulcer Disease', 'Severe Heart Failure']
  },
  {
    id: 'drg-005',
    genericName: 'Amlodipine Besylate',
    brandName: 'Norvasc',
    category: 'Antihypertensives',
    dosageForm: 'Tablet',
    strength: '10mg',
    unitPrice: 1800,
    stockOnHand: 120,
    reorderLevel: 30,
    batchNumber: 'AML-2026-D8',
    expiryDate: '2027-11-30',
    activeIngredients: ['Amlodipine Besylate'],
    contraindications: ['Severe Hypotension', 'Cardiogenic Shock']
  },
  {
    id: 'drg-006',
    genericName: 'IV Furosemide',
    brandName: 'Lasix IV',
    category: 'Antihypertensives',
    dosageForm: 'Injection',
    strength: '20mg/2mL',
    unitPrice: 1500,
    stockOnHand: 65,
    reorderLevel: 25,
    batchNumber: 'FUR-2026-F3',
    expiryDate: '2027-05-31',
    activeIngredients: ['Furosemide'],
    contraindications: ['Sulphonamide Allergy', 'Anuria', 'Electrolyte Depletion']
  },
  {
    id: 'drg-007',
    genericName: 'Metformin Hydrochloride',
    brandName: 'Glucophage',
    category: 'Antidiabetics',
    dosageForm: 'Tablet',
    strength: '500mg',
    unitPrice: 1100,
    stockOnHand: 210,
    reorderLevel: 60,
    batchNumber: 'MET-2026-G1',
    expiryDate: '2028-03-31',
    activeIngredients: ['Metformin Hydrochloride'],
    contraindications: ['Severe Renal Impairment (eGFR < 30)', 'Acute Metabolic Acidosis']
  },
  {
    id: 'drg-008',
    genericName: 'Artemether / Lumefantrine',
    brandName: 'Coartem',
    category: 'Antimalarials',
    dosageForm: 'Tablet',
    strength: '20/120mg (80/480mg Forte)',
    unitPrice: 3200,
    stockOnHand: 95,
    reorderLevel: 40,
    batchNumber: 'COA-2026-H7',
    expiryDate: '2027-09-30',
    activeIngredients: ['Artemether', 'Lumefantrine'],
    contraindications: ['First Trimester Pregnancy (use Quinine)', 'Severe Hypokalemia']
  },
  {
    id: 'drg-009',
    genericName: 'IV Normal Saline 0.9%',
    brandName: 'Sodium Chloride IV',
    category: 'Fluids & Electrolytes',
    dosageForm: 'Infusion (IV)',
    strength: '500mL',
    unitPrice: 1200,
    stockOnHand: 0, // Out of Stock trigger
    reorderLevel: 30,
    batchNumber: 'NS-2026-I4',
    expiryDate: '2028-12-31',
    activeIngredients: ['Sodium Chloride 0.9%'],
    contraindications: ['Hypernatremia', 'Congestive Heart Failure Fluid Overload']
  },
  {
    id: 'drg-010',
    genericName: 'IV Ceftriaxone',
    brandName: 'Rocephin',
    category: 'Antibiotics',
    dosageForm: 'Injection',
    strength: '1g Vial',
    unitPrice: 4200,
    stockOnHand: 55,
    reorderLevel: 20,
    batchNumber: 'CEF-2026-K9',
    expiryDate: '2027-10-31',
    activeIngredients: ['Ceftriaxone Sodium'],
    contraindications: ['Cephalosporin Hypersensitivity', 'Severe Penicillin Anaphylaxis']
  }
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-001',
    prescriptionNumber: 'RX-2026-004101',
    patientId: 'p-002',
    patientName: 'Amina Bello',
    hospitalNumber: 'HIMS/2026/000102',
    age: 32,
    gender: 'Female',
    patientType: 'Inpatient',
    wardName: 'Female Surgical Ward (FSW)',
    bedNumber: 'FSW-01',
    prescriberName: 'Dr. K. Ibrahim (Chief Surgeon)',
    prescriberDepartment: 'General Surgery',
    prescribedAt: '2026-09-28T11:30:00Z',
    status: 'pending',
    knownAllergies: ['NSAIDs (Bronchospasm)'],
    payerScheme: 'NHIA',
    paymentStatus: 'paid',
    clinicalNotes: 'Post-op Laparoscopic Cholecystectomy discharge Take-Home Medications (TTO).',
    items: [
      {
        id: 'rxi-01',
        drugId: 'drg-003',
        drugName: 'Panadol Extra',
        genericName: 'Paracetamol',
        dosageForm: 'Tablet',
        strength: '500mg',
        dosage: '1g (2 tablets)',
        route: 'Oral',
        frequency: 'TDS (8-hourly)',
        durationDays: 5,
        quantityPrescribed: 30,
        quantityDispensed: 0,
        instructions: 'Take 2 tablets three times daily after food for mild pain.',
        isDispensed: false,
        unitPrice: 350
      },
      {
        id: 'rxi-02',
        drugId: 'drg-002',
        drugName: 'Cipro-Denk',
        genericName: 'Ciprofloxacin',
        dosageForm: 'Tablet',
        strength: '500mg',
        dosage: '500mg (1 tablet)',
        route: 'Oral',
        frequency: 'BD (12-hourly)',
        durationDays: 5,
        quantityPrescribed: 10,
        quantityDispensed: 0,
        instructions: 'Complete full course. Drink plenty of water.',
        isDispensed: false,
        unitPrice: 1200
      }
    ]
  },
  {
    id: 'rx-002',
    prescriptionNumber: 'RX-2026-004102',
    patientId: 'p-001',
    patientName: 'Chidi Okafor',
    hospitalNumber: 'HIMS/2026/000101',
    age: 45,
    gender: 'Male',
    patientType: 'Inpatient',
    wardName: 'Male Medical Ward (MMW)',
    bedNumber: 'MMW-01',
    prescriberName: 'Dr. O. Adeleke (Cardiologist)',
    prescriberDepartment: 'Internal Medicine',
    prescribedAt: '2026-09-28T14:15:00Z',
    status: 'pending',
    knownAllergies: ['Penicillin', 'Sulphonamides'],
    payerScheme: 'Cash',
    paymentStatus: 'paid',
    clinicalNotes: 'Acute LVF secondary to hypertensive emergency. Stat doses administered on ward.',
    items: [
      {
        id: 'rxi-03',
        drugId: 'drg-006',
        drugName: 'Lasix IV',
        genericName: 'IV Furosemide',
        dosageForm: 'Injection',
        strength: '20mg/2mL',
        dosage: '40mg (2 ampoules)',
        route: 'IV',
        frequency: 'TDS (8-hourly)',
        durationDays: 2,
        quantityPrescribed: 12,
        quantityDispensed: 0,
        instructions: 'Slow IV injection over 5 minutes. Monitor urine output.',
        isDispensed: false,
        unitPrice: 1500
      },
      {
        id: 'rxi-04',
        drugId: 'drg-005',
        drugName: 'Norvasc',
        genericName: 'Amlodipine Besylate',
        dosageForm: 'Tablet',
        strength: '10mg',
        dosage: '10mg (1 tablet)',
        route: 'Oral',
        frequency: 'OD Mane (Daily morning)',
        durationDays: 30,
        quantityPrescribed: 30,
        quantityDispensed: 0,
        instructions: 'Take 1 tablet every morning with breakfast.',
        isDispensed: false,
        unitPrice: 1800
      }
    ]
  },
  {
    id: 'rx-003',
    prescriptionNumber: 'RX-2026-004099',
    patientId: 'p-003',
    patientName: 'David Adeyemi',
    hospitalNumber: 'HIMS/2026/000103',
    age: 58,
    gender: 'Male',
    patientType: 'Outpatient',
    prescriberName: 'Dr. N. Okonjo',
    prescriberDepartment: 'GOPD / Endocrinology',
    prescribedAt: '2026-09-28T09:30:00Z',
    status: 'dispensed',
    knownAllergies: ['None Reported'],
    payerScheme: 'Cash',
    paymentStatus: 'paid',
    dispensedAt: '2026-09-28T10:15:00Z',
    dispensedBy: 'Pharm. U. Chukwu, B.Pharm',
    clinicalNotes: 'Monthly routine refill for Type 2 Diabetes.',
    items: [
      {
        id: 'rxi-05',
        drugId: 'drg-007',
        drugName: 'Glucophage',
        genericName: 'Metformin Hydrochloride',
        dosageForm: 'Tablet',
        strength: '500mg',
        dosage: '1000mg (2 tablets)',
        route: 'Oral',
        frequency: 'BD (12-hourly)',
        durationDays: 30,
        quantityPrescribed: 60,
        quantityDispensed: 60,
        instructions: 'Take with or immediately after meals to reduce GI upset.',
        isDispensed: true,
        unitPrice: 1100
      }
    ]
  },
  {
    id: 'rx-004',
    prescriptionNumber: 'RX-2026-004105',
    patientId: 'p-012',
    patientName: 'Kelechi Eze',
    hospitalNumber: 'HIMS/2026/000112',
    age: 26,
    gender: 'Male',
    patientType: 'Outpatient',
    prescriberName: 'Dr. C. Eze',
    prescriberDepartment: 'General Outpatient (GOPD)',
    prescribedAt: '2026-09-28T15:20:00Z',
    status: 'pending',
    knownAllergies: ['Penicillin'], // ALLERGY CONFLICT TEST CASE!
    payerScheme: 'Cash',
    paymentStatus: 'pending',
    clinicalNotes: 'Upper respiratory tract infection.',
    items: [
      {
        id: 'rxi-06',
        drugId: 'drg-001', // Augmentin (Amoxicillin) -> TRIGGERS ALLERGY ALERT!
        drugName: 'Augmentin',
        genericName: 'Amoxicillin / Clavulanic Acid',
        dosageForm: 'Tablet',
        strength: '625mg',
        dosage: '625mg (1 tablet)',
        route: 'Oral',
        frequency: 'BD (12-hourly)',
        durationDays: 7,
        quantityPrescribed: 14,
        quantityDispensed: 0,
        instructions: 'Take 1 tablet every 12 hours at the start of a meal.',
        isDispensed: false,
        unitPrice: 2800
      }
    ]
  }
];
