import {
  GlobalSystemConfig,
  PermissionDefinition,
  RolePermissionsMatrix,
  UserAccount,
} from './types';

export const INITIAL_SYSTEM_CONFIG: GlobalSystemConfig = {
  facility: {
    hospitalName: 'National Specialist Teaching Hospital, Abuja',
    facilityLevel: 'Tertiary Teaching Hospital',
    accreditationCode: 'MDCN-FCT-2026-981',
    registrationNumber: 'RC-884192 / MoH-FCT-041',
    physicalAddress: 'Plot 1044 Medical District Way, Central Business District, Abuja',
    state: 'Federal Capital Territory',
    country: 'Nigeria',
    officialPhone: '+234 9 291 4000',
    emergencyHotline: '+234 800 911 0000',
    officialEmail: 'info@nsthabuja.gov.ng',
    defaultCurrency: 'NGN (₦)',
    fiscalYear: '2026',
  },
  security: {
    sessionTimeoutMinutes: 30,
    maxFailedLoginAttempts: 5,
    passwordExpiryDays: 90,
    enforceTwoFactorForFinancialRoles: true,
    allowEmergencyOverrideLogging: true,
    maintenanceMode: false,
    inpatientDepositGate: 'SOFT_WARNING',
    dischargeChecklistEnforcement: 'STRICT_100_PERCENT',
  },
  lastUpdatedBy: 'Engr. A. Yusuf (System Administrator)',
  lastUpdatedAt: '2026-10-01T08:30:00Z',
};

export const MODULE_PERMISSIONS_CATALOG: PermissionDefinition[] = [
  // Medical Records
  { id: 'medicalrecords:read', module: 'medicalrecords', moduleLabel: 'Medical Records', action: 'READ', description: 'Search Master Patient Index and view demographics' },
  { id: 'medicalrecords:write', module: 'medicalrecords', moduleLabel: 'Medical Records', action: 'WRITE', description: 'Register new patients and issue ID cards' },
  // Nursing
  { id: 'nursing:read', module: 'nursing', moduleLabel: 'Nursing Services', action: 'READ', description: 'View ward bed maps, vitals, and handover logs' },
  { id: 'nursing:write', module: 'nursing', moduleLabel: 'Nursing Services', action: 'WRITE', description: 'Record patient vitals, admissions, and nursing notes' },
  { id: 'nursing:approve', module: 'nursing', moduleLabel: 'Nursing Services', action: 'APPROVE', description: 'Sign dual-nurse shift handovers and verify discharge checklist' },
  // Billing
  { id: 'billing:read', module: 'billing', moduleLabel: 'Accounts & Billing', action: 'READ', description: 'View patient invoices, tariff fees, and outstanding aging' },
  { id: 'billing:write', module: 'billing', moduleLabel: 'Accounts & Billing', action: 'WRITE', description: 'Generate patient invoices and record receipt payments' },
  { id: 'billing:approve', module: 'billing', moduleLabel: 'Accounts & Billing', action: 'APPROVE', description: 'Authorize bill adjustments and discount waives' },
  { id: 'billing:delete_soft', module: 'billing', moduleLabel: 'Accounts & Billing', action: 'DELETE_SOFT', description: 'Cancel invoices with soft-delete and mandatory audit reason' },
  // Pharmacy
  { id: 'pharmacy:read', module: 'pharmacy', moduleLabel: 'Pharmacy', action: 'READ', description: 'View prescription orders and drug formularies' },
  { id: 'pharmacy:write', module: 'pharmacy', moduleLabel: 'Pharmacy', action: 'WRITE', description: 'Dispense medications and update stock balances' },
  // Accounting
  { id: 'accounting:read', module: 'accounting', moduleLabel: 'General Ledger', action: 'READ', description: 'View Chart of Accounts and financial statements' },
  { id: 'accounting:write', module: 'accounting', moduleLabel: 'General Ledger', action: 'WRITE', description: 'Draft journal vouchers and reconcile cashier receipts' },
  { id: 'accounting:approve', module: 'accounting', moduleLabel: 'General Ledger', action: 'APPROVE', description: 'Chief Accountant authorization for financial ledger postings' },
  // Laboratory
  { id: 'laboratory:read', module: 'laboratory', moduleLabel: 'Laboratory (LIS)', action: 'READ', description: 'View test requests and analyzer result logs' },
  { id: 'laboratory:write', module: 'laboratory', moduleLabel: 'Laboratory (LIS)', action: 'WRITE', description: 'Enter bench test values and run analyzer sync' },
  { id: 'laboratory:approve', module: 'laboratory', moduleLabel: 'Laboratory (LIS)', action: 'APPROVE', description: 'Pathologist clinical sign-off and verification' },
  // Radiology
  { id: 'radiology:read', module: 'radiology', moduleLabel: 'Radiology / PACS', action: 'READ', description: 'View DICOM imaging orders and modality schedules' },
  { id: 'radiology:approve', module: 'radiology', moduleLabel: 'Radiology / PACS', action: 'APPROVE', description: 'Radiologist verification and diagnostic sign-off' },
  // Inventory
  { id: 'inventory:read', module: 'inventory', moduleLabel: 'Inventory & Procurement', action: 'READ', description: 'View master catalog, stock levels, and purchase orders' },
  { id: 'inventory:write', module: 'inventory', moduleLabel: 'Inventory & Procurement', action: 'WRITE', description: 'Create purchase orders, record GRN, and dispatch buffer stock' },
  { id: 'inventory:approve', module: 'inventory', moduleLabel: 'Inventory & Procurement', action: 'APPROVE', description: 'Approve vendor purchase orders and procurement budgets' },
  // Audit
  { id: 'audit:read', module: 'audit', moduleLabel: 'Audit Department', action: 'READ', description: 'Inspect append-only clinical and financial audit logs' },
  { id: 'audit:approve', module: 'audit', moduleLabel: 'Audit Department', action: 'APPROVE', description: 'Sign off forensic anomaly investigation reports' },
  // Administration
  { id: 'admin:read', module: 'admin', moduleLabel: 'System Administration', action: 'READ', description: 'Inspect global settings, user accounts, and security logs' },
  { id: 'admin:write', module: 'admin', moduleLabel: 'System Administration', action: 'WRITE', description: 'Provision user accounts and configure facility parameters' },
  { id: 'admin:admin_override', module: 'admin', moduleLabel: 'System Administration', action: 'ADMIN_OVERRIDE', description: 'Emergency administrative master override with mandatory logging' },
];

export const INITIAL_ROLE_MATRICES: RolePermissionsMatrix[] = [
  {
    role: 'ADMIN',
    roleLabel: 'System Administrator (ICT)',
    description: 'Full administrative access for user provisioning, security parameters, and facility configuration.',
    userCount: 2,
    permissions: MODULE_PERMISSIONS_CATALOG.map((p) => p.id),
  },
  {
    role: 'DOCTOR',
    roleLabel: 'Consultant / Medical Doctor',
    description: 'Clinical consultation, prescription ordering, patient admission, and surgical notes.',
    userCount: 14,
    permissions: [
      'medicalrecords:read',
      'nursing:read',
      'nursing:write',
      'pharmacy:read',
      'laboratory:read',
      'radiology:read',
    ],
  },
  {
    role: 'NURSE',
    roleLabel: 'Registered Nurse / Ward Matron',
    description: 'Patient admissions, vitals recording, nursing care plans, and shift handovers.',
    userCount: 28,
    permissions: [
      'medicalrecords:read',
      'nursing:read',
      'nursing:write',
      'nursing:approve',
      'pharmacy:read',
      'laboratory:read',
    ],
  },
  {
    role: 'PHARMACIST',
    roleLabel: 'Clinical Pharmacist',
    description: 'Prescription intake verification, formulary stock management, and drug dispensing.',
    userCount: 6,
    permissions: [
      'medicalrecords:read',
      'pharmacy:read',
      'pharmacy:write',
      'inventory:read',
    ],
  },
  {
    role: 'ACCOUNTANT',
    roleLabel: 'Hospital Accountant / Cashier',
    description: 'Cashier receipts collection, patient invoice generation, and billing entries.',
    userCount: 8,
    permissions: [
      'billing:read',
      'billing:write',
      'accounting:read',
      'accounting:write',
    ],
  },
  {
    role: 'CHIEF_ACCOUNTANT',
    roleLabel: 'Chief Financial Officer / Chief Accountant',
    description: 'Financial ledger authorization, tariff adjustments, and journal voucher approvals.',
    userCount: 1,
    permissions: [
      'billing:read',
      'billing:write',
      'billing:approve',
      'billing:delete_soft',
      'accounting:read',
      'accounting:write',
      'accounting:approve',
      'inventory:approve',
    ],
  },
  {
    role: 'AUDITOR',
    roleLabel: 'Internal Hospital Auditor',
    description: 'Independent inspection of append-only clinical and financial transaction logs.',
    userCount: 3,
    permissions: [
      'audit:read',
      'audit:approve',
      'billing:read',
      'accounting:read',
      'inventory:read',
    ],
  },
  {
    role: 'LAB_SCIENTIST',
    roleLabel: 'Medical Laboratory Scientist',
    description: 'Specimen barcode intake, analyzer test entry, and pathologist sign-off.',
    userCount: 9,
    permissions: [
      'medicalrecords:read',
      'laboratory:read',
      'laboratory:write',
      'laboratory:approve',
    ],
  },
  {
    role: 'RADIOLOGIST',
    roleLabel: 'Consultant Radiologist',
    description: 'DICOM imaging study interpretation and diagnostic verification.',
    userCount: 4,
    permissions: [
      'medicalrecords:read',
      'radiology:read',
      'radiology:approve',
    ],
  },
  {
    role: 'STOREKEEPER',
    roleLabel: 'Central Storekeeper / Material Manager',
    description: 'Warehouse goods receipt (GRN), quality batch intake, and ward buffer distribution.',
    userCount: 5,
    permissions: [
      'inventory:read',
      'inventory:write',
    ],
  },
  {
    role: 'RECORDS_OFFICER',
    roleLabel: 'Health Information / Records Officer',
    description: 'Patient master index lookup, registration, and demographic maintenance.',
    userCount: 11,
    permissions: [
      'medicalrecords:read',
      'medicalrecords:write',
    ],
  },
  {
    role: 'NHIA_OFFICER',
    roleLabel: 'NHIA / Health Insurance Desk Officer',
    description: 'HMO eligibility verification, tariff pre-authorizations, and claims bundling.',
    userCount: 4,
    permissions: [
      'medicalrecords:read',
      'billing:read',
    ],
  },
];

export const INITIAL_USER_ACCOUNTS: UserAccount[] = [
  {
    id: 'USR-2026-001',
    username: 'admin.yusuf',
    email: 'a.yusuf@nsthabuja.gov.ng',
    firstName: 'Ahmed',
    lastName: 'Yusuf',
    phoneNumber: '+234 803 111 2233',
    role: 'ADMIN',
    department: 'ICT & Health Informatics',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-09T08:15:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-10-01T12:00:00Z',
  },
  {
    id: 'USR-2026-002',
    username: 'dr.adebayo',
    email: 'o.adebayo@nsthabuja.gov.ng',
    firstName: 'Olumide',
    lastName: 'Adebayo',
    phoneNumber: '+234 802 334 4556',
    role: 'DOCTOR',
    department: 'General Outpatient & Internal Medicine',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-09T07:45:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'USR-2026-003',
    username: 'matron.nwosu',
    email: 'c.nwosu@nsthabuja.gov.ng',
    firstName: 'Chioma',
    lastName: 'Nwosu',
    phoneNumber: '+234 805 778 8990',
    role: 'NURSE',
    department: 'Nursing Administration & Male Surgical',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-09T06:50:00Z',
    twoFactorEnabled: false,
    createdAt: '2026-01-15T08:30:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'USR-2026-004',
    username: 'pharm.bello',
    email: 'd.bello@nsthabuja.gov.ng',
    firstName: 'Danjuma',
    lastName: 'Bello',
    phoneNumber: '+234 809 123 4567',
    role: 'PHARMACIST',
    department: 'Pharmacy & Quality Assurance',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-08T15:20:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-01-18T11:00:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
  {
    id: 'USR-2026-005',
    username: 'cfo.ibrahim',
    email: 'k.ibrahim@nsthabuja.gov.ng',
    firstName: 'Kabiru',
    lastName: 'Ibrahim',
    phoneNumber: '+234 803 998 8776',
    role: 'CHIEF_ACCOUNTANT',
    department: 'Finance & Accounts',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-08T16:10:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-09-28T09:15:00Z',
  },
  {
    id: 'USR-2026-006',
    username: 'auditor.ezekiel',
    email: 'f.ezekiel@nsthabuja.gov.ng',
    firstName: 'Folake',
    lastName: 'Ezekiel',
    phoneNumber: '+234 802 445 5667',
    role: 'AUDITOR',
    department: 'Internal Audit Department',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-09T08:05:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-09-30T14:40:00Z',
  },
  {
    id: 'USR-2026-007',
    username: 'store.okafor',
    email: 'b.okafor@nsthabuja.gov.ng',
    firstName: 'Barnabas',
    lastName: 'Okafor',
    phoneNumber: '+234 806 223 3445',
    role: 'STOREKEEPER',
    department: 'Central Medical Stores',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-08T14:00:00Z',
    twoFactorEnabled: false,
    createdAt: '2026-02-10T13:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'USR-2026-008',
    username: 'sci.garba',
    email: 'm.garba@nsthabuja.gov.ng',
    firstName: 'Mohammed',
    lastName: 'Garba',
    phoneNumber: '+234 807 889 9001',
    role: 'LAB_SCIENTIST',
    department: 'Pathology & Haematology Lab',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-08T13:30:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-02-15T09:40:00Z',
    updatedAt: '2026-08-14T11:20:00Z',
  },
  {
    id: 'USR-2026-009',
    username: 'cashier.uchenna',
    email: 'u.okoye@nsthabuja.gov.ng',
    firstName: 'Uchenna',
    lastName: 'Okoye',
    phoneNumber: '+234 803 776 6554',
    role: 'ACCOUNTANT',
    department: 'Revenue & Cashier Office',
    status: 'LOCKED',
    failedLoginAttempts: 5,
    lastLoginAt: '2026-10-06T18:22:00Z',
    twoFactorEnabled: false,
    createdAt: '2026-03-01T12:00:00Z',
    updatedAt: '2026-10-06T18:25:00Z',
  },
  {
    id: 'USR-2026-010',
    username: 'rad.onyeama',
    email: 's.onyeama@nsthabuja.gov.ng',
    firstName: 'Stella',
    lastName: 'Onyeama',
    phoneNumber: '+234 809 665 5443',
    role: 'RADIOLOGIST',
    department: 'Radiology & Imaging',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    lastLoginAt: '2026-10-08T11:15:00Z',
    twoFactorEnabled: true,
    createdAt: '2026-03-10T14:15:00Z',
    updatedAt: '2026-09-02T16:45:00Z',
  },
];
