import { StaffProfile, DutyShift, LeaveRequest } from './types';

export const INITIAL_STAFF: StaffProfile[] = [
  {
    id: 'STF-2026-001',
    staffNumber: 'HOSP/DOC/084',
    firstName: 'Fatima',
    lastName: 'Abdullahi',
    gender: 'FEMALE',
    dateOfBirth: '1984-05-14',
    email: 'f.abdullahi@hospital.gov.ng',
    phone: '08031234567',
    department: 'Obstetrics & Gynaecology',
    cadre: 'MEDICAL',
    designation: 'Chief Consultant Obstetrician',
    employmentType: 'FULL_TIME',
    dateJoined: '2016-03-01',
    licenseType: 'MDCN',
    licenseNumber: 'MDCN-48192',
    licenseExpiryDate: '2027-12-31',
    licenseStatus: 'ACTIVE',
    status: 'ACTIVE',
    bankDetails: { bankName: 'Zenith Bank', accountNumber: '2081192831' }
  },
  {
    id: 'STF-2026-002',
    staffNumber: 'HOSP/DOC/092',
    firstName: 'Kenneth',
    lastName: 'Okafor',
    gender: 'MALE',
    dateOfBirth: '1988-11-20',
    email: 'k.okafor@hospital.gov.ng',
    phone: '08029876543',
    department: 'Internal Medicine',
    cadre: 'MEDICAL',
    designation: 'Senior Registrar (Cardiology)',
    employmentType: 'FULL_TIME',
    dateJoined: '2020-07-15',
    licenseType: 'MDCN',
    licenseNumber: 'MDCN-61029',
    licenseExpiryDate: '2026-11-15',
    licenseStatus: 'EXPIRING_SOON',
    status: 'ACTIVE',
    bankDetails: { bankName: 'First Bank of Nigeria', accountNumber: '3049182741' }
  },
  {
    id: 'STF-2026-003',
    staffNumber: 'HOSP/NUR/115',
    firstName: 'Grace',
    lastName: 'Okafor',
    gender: 'FEMALE',
    dateOfBirth: '1990-03-25',
    email: 'g.okafor@hospital.gov.ng',
    phone: '08051239876',
    department: 'Nursing Services',
    cadre: 'NURSING',
    designation: 'Principal Nursing Officer (Ward 4)',
    employmentType: 'FULL_TIME',
    dateJoined: '2018-09-01',
    licenseType: 'NMCN',
    licenseNumber: 'NMCN-RN-99214',
    licenseExpiryDate: '2027-08-30',
    licenseStatus: 'ACTIVE',
    status: 'ACTIVE',
    bankDetails: { bankName: 'GTBank', accountNumber: '0129384756' }
  },
  {
    id: 'STF-2026-004',
    staffNumber: 'HOSP/NUR/142',
    firstName: 'Blessing',
    lastName: 'Chukwuma',
    gender: 'FEMALE',
    dateOfBirth: '1995-08-10',
    email: 'b.chukwuma@hospital.gov.ng',
    phone: '08169988776',
    department: 'Accident & Emergency',
    cadre: 'NURSING',
    designation: 'Senior Nursing Officer (Triage)',
    employmentType: 'FULL_TIME',
    dateJoined: '2021-02-10',
    licenseType: 'NMCN',
    licenseNumber: 'NMCN-RM-10294',
    licenseExpiryDate: '2028-01-15',
    licenseStatus: 'ACTIVE',
    status: 'ACTIVE',
    bankDetails: { bankName: 'Access Bank', accountNumber: '1482910482' }
  },
  {
    id: 'STF-2026-005',
    staffNumber: 'HOSP/PHAR/031',
    firstName: 'Ibrahim',
    lastName: 'Sani',
    gender: 'MALE',
    dateOfBirth: '1987-04-12',
    email: 'i.sani@hospital.gov.ng',
    phone: '08034455667',
    department: 'Pharmacy',
    cadre: 'PHARMACY',
    designation: 'Assistant Chief Pharmacist',
    employmentType: 'FULL_TIME',
    dateJoined: '2015-11-01',
    licenseType: 'PCN',
    licenseNumber: 'PCN-REG-55201',
    licenseExpiryDate: '2027-05-31',
    licenseStatus: 'ACTIVE',
    status: 'ACTIVE',
    bankDetails: { bankName: 'UBA', accountNumber: '2093847561' }
  },
  {
    id: 'STF-2026-006',
    staffNumber: 'HOSP/LAB/045',
    firstName: 'Chidinma',
    lastName: 'Eze',
    gender: 'FEMALE',
    dateOfBirth: '1992-09-18',
    email: 'c.eze@hospital.gov.ng',
    phone: '08077889900',
    department: 'Laboratory (Haematology)',
    cadre: 'LABORATORY',
    designation: 'Medical Laboratory Scientist II',
    employmentType: 'FULL_TIME',
    dateJoined: '2022-04-01',
    licenseType: 'MLSCN',
    licenseNumber: 'MLSCN-88410',
    licenseExpiryDate: '2026-10-31',
    licenseStatus: 'EXPIRING_SOON',
    status: 'ACTIVE',
    bankDetails: { bankName: 'Stanbic IBTC', accountNumber: '0039281745' }
  },
  {
    id: 'STF-2026-007',
    staffNumber: 'HOSP/DOC/071',
    firstName: 'Amina',
    lastName: 'Bello',
    gender: 'FEMALE',
    dateOfBirth: '1989-12-05',
    email: 'a.bello@hospital.gov.ng',
    phone: '08091122334',
    department: 'Accident & Emergency',
    cadre: 'MEDICAL',
    designation: 'Consultant Emergency Physician',
    employmentType: 'FULL_TIME',
    dateJoined: '2019-06-15',
    licenseType: 'MDCN',
    licenseNumber: 'MDCN-52918',
    licenseExpiryDate: '2027-11-30',
    licenseStatus: 'ACTIVE',
    status: 'ACTIVE',
    bankDetails: { bankName: 'Zenith Bank', accountNumber: '2104928172' }
  },
  {
    id: 'STF-2026-008',
    staffNumber: 'HOSP/ACC/019',
    firstName: 'Bello',
    lastName: 'Danjuma',
    gender: 'MALE',
    dateOfBirth: '1982-01-30',
    email: 'b.danjuma@hospital.gov.ng',
    phone: '08023344556',
    department: 'Finance & Accounts',
    cadre: 'ADMINISTRATIVE',
    designation: 'Principal Accountant (Revenue)',
    employmentType: 'FULL_TIME',
    dateJoined: '2014-08-01',
    licenseType: 'NOT_APPLICABLE',
    licenseStatus: 'NOT_APPLICABLE',
    status: 'ON_LEAVE',
    bankDetails: { bankName: 'First Bank of Nigeria', accountNumber: '3092817462' }
  },
  {
    id: 'STF-2026-009',
    staffNumber: 'HOSP/MOR/004',
    firstName: 'Usman',
    lastName: 'Garba',
    gender: 'MALE',
    dateOfBirth: '1985-07-22',
    email: 'u.garba@hospital.gov.ng',
    phone: '08061177889',
    department: 'Mortuary & Pathology Services',
    cadre: 'ALLIED_HEALTH',
    designation: 'Senior Mortuary Technician',
    employmentType: 'FULL_TIME',
    dateJoined: '2017-10-15',
    licenseType: 'NOT_APPLICABLE',
    licenseStatus: 'NOT_APPLICABLE',
    status: 'ACTIVE',
    bankDetails: { bankName: 'Fidelity Bank', accountNumber: '5092837162' }
  }
];

export const INITIAL_SHIFTS: DutyShift[] = [
  {
    id: 'SHF-2026-101',
    department: 'Nursing Services',
    wardOrUnit: 'Male Medical Ward (Ward 4)',
    staffId: 'STF-2026-003',
    staffName: 'Grace Okafor',
    staffRole: 'Principal Nursing Officer',
    shiftDate: '2026-10-08',
    shiftType: 'MORNING',
    startTime: '07:30',
    endTime: '15:30',
    status: 'SCHEDULED',
    notes: 'Ward in-charge nurse for morning rounds'
  },
  {
    id: 'SHF-2026-102',
    department: 'Accident & Emergency',
    wardOrUnit: 'Triage Desk',
    staffId: 'STF-2026-004',
    staffName: 'Blessing Chukwuma',
    staffRole: 'Senior Nursing Officer',
    shiftDate: '2026-10-08',
    shiftType: 'AFTERNOON',
    startTime: '15:30',
    endTime: '21:30',
    status: 'SCHEDULED',
    notes: 'A&E Red/Yellow triage lead'
  },
  {
    id: 'SHF-2026-103',
    department: 'Obstetrics & Gynaecology',
    wardOrUnit: 'Labor & Delivery Suite',
    staffId: 'STF-2026-001',
    staffName: 'Dr. Fatima Abdullahi',
    staffRole: 'Chief Consultant',
    shiftDate: '2026-10-08',
    shiftType: 'CALL_DUTY',
    startTime: '08:00',
    endTime: '08:00',
    status: 'SCHEDULED',
    notes: '1st On-Call Consultant for Emergency Caesarean Sections'
  },
  {
    id: 'SHF-2026-104',
    department: 'Pharmacy',
    wardOrUnit: 'Main Outpatient Dispensary',
    staffId: 'STF-2026-005',
    staffName: 'Ibrahim Sani',
    staffRole: 'Assistant Chief Pharmacist',
    shiftDate: '2026-10-08',
    shiftType: 'MORNING',
    startTime: '08:00',
    endTime: '16:00',
    status: 'SCHEDULED',
    notes: 'Controlled drug dispensary custodian'
  },
  {
    id: 'SHF-2026-105',
    department: 'Laboratory',
    wardOrUnit: 'Haematology & Blood Bank',
    staffId: 'STF-2026-006',
    staffName: 'Chidinma Eze',
    staffRole: 'MLS II',
    shiftDate: '2026-10-08',
    shiftType: 'NIGHT',
    startTime: '21:30',
    endTime: '07:30',
    status: 'SCHEDULED',
    notes: 'Stat crossmatch & urgent emergency donor screening'
  },
  {
    id: 'SHF-2026-106',
    department: 'Accident & Emergency',
    wardOrUnit: 'Resuscitation Bay',
    staffId: 'STF-2026-007',
    staffName: 'Dr. Amina Bello',
    staffRole: 'Consultant',
    shiftDate: '2026-10-08',
    shiftType: 'MORNING',
    startTime: '08:00',
    endTime: '16:00',
    status: 'SCHEDULED',
    notes: 'Trauma resuscitation lead'
  }
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'LEV-2026-041',
    staffId: 'STF-2026-008',
    staffName: 'Bello Danjuma',
    department: 'Finance & Accounts',
    leaveType: 'ANNUAL',
    startDate: '2026-10-05',
    endDate: '2026-10-19',
    totalDays: 14,
    reason: 'Approved annual vacation leave',
    reliefStaffId: 'STF-2026-015',
    reliefStaffName: 'Musa Aliyu (Accountant II)',
    status: 'APPROVED',
    approvedBy: 'Director of Finance & Administration',
    approvalNotes: 'Delegation letter HOSP-ED-2026-092 issued to proxy',
    appliedAt: '2026-09-20T10:00:00Z',
    reviewedAt: '2026-09-25T14:30:00Z'
  },
  {
    id: 'LEV-2026-042',
    staffId: 'STF-2026-002',
    staffName: 'Dr. Kenneth Okafor',
    department: 'Internal Medicine',
    leaveType: 'STUDY',
    startDate: '2026-10-25',
    endDate: '2026-10-30',
    totalDays: 5,
    reason: 'Attendance and paper presentation at Nigerian Cardiac Society Annual General Meeting',
    reliefStaffId: 'STF-2026-018',
    reliefStaffName: 'Dr. Y. K. Garba',
    status: 'PENDING_HOD',
    appliedAt: '2026-10-06T11:15:00Z'
  },
  {
    id: 'LEV-2026-043',
    staffId: 'STF-2026-006',
    staffName: 'Chidinma Eze',
    department: 'Laboratory',
    leaveType: 'CASUAL',
    startDate: '2026-10-15',
    endDate: '2026-10-16',
    totalDays: 2,
    reason: 'Family emergency requiring travel to Enugu State',
    reliefStaffId: 'STF-2026-022',
    reliefStaffName: 'Samuel Ade (MLS)',
    status: 'PENDING_HOD',
    appliedAt: '2026-10-07T08:45:00Z'
  }
];
