import {
  ClinicalCensusData,
  FinancialReportData,
  OperationalMetricsData,
} from './types';

export const INITIAL_FINANCIAL_REPORT: FinancialReportData = {
  period: 'THIS_MONTH',
  dateRange: {
    startDate: '2026-10-01',
    endDate: '2026-10-31',
  },
  totalRevenue: 28450000,
  formattedTotalRevenue: '₦28,450,000.00',
  totalCollected: 25180000,
  formattedTotalCollected: '₦25,180,000.00',
  totalOutstanding: 3270000,
  formattedTotalOutstanding: '₦3,270,000.00',
  collectionRate: 88.5,
  departmentRevenue: [
    {
      department: 'Central Pharmacy',
      revenue: 9800000,
      formattedRevenue: '₦9,800,000.00',
      percentage: 34.4,
      transactionCount: 2840,
    },
    {
      department: 'Inpatient Wards (Bed & Nursing)',
      revenue: 6400000,
      formattedRevenue: '₦6,400,000.00',
      percentage: 22.5,
      transactionCount: 312,
    },
    {
      department: 'Operating Theatre & Anaesthesia',
      revenue: 4200000,
      formattedRevenue: '₦4,200,000.00',
      percentage: 14.8,
      transactionCount: 78,
    },
    {
      department: 'Clinical Diagnostic Laboratory',
      revenue: 3500000,
      formattedRevenue: '₦3,500,000.00',
      percentage: 12.3,
      transactionCount: 1640,
    },
    {
      department: 'Radiology & Imaging',
      revenue: 2600000,
      formattedRevenue: '₦2,600,000.00',
      percentage: 9.1,
      transactionCount: 520,
    },
    {
      department: 'GOPD Consultation & Triage',
      revenue: 1200000,
      formattedRevenue: '₦1,200,000.00',
      percentage: 4.2,
      transactionCount: 1980,
    },
    {
      department: 'Mortuary & Pathology Services',
      revenue: 750000,
      formattedRevenue: '₦750,000.00',
      percentage: 2.7,
      transactionCount: 24,
    },
  ],
  paymentChannels: [
    {
      channel: 'POS',
      label: 'Point of Sale (Debit Card)',
      amount: 11950000,
      formattedAmount: '₦11,950,000.00',
      percentage: 47.5,
      transactionCount: 2940,
    },
    {
      channel: 'BANK_TRANSFER',
      label: 'Direct Bank Transfer',
      amount: 7810000,
      formattedAmount: '₦7,810,000.00',
      percentage: 31.0,
      transactionCount: 1120,
    },
    {
      channel: 'CASH',
      label: 'Cashier Cash Collections',
      amount: 3260000,
      formattedAmount: '₦3,260,000.00',
      percentage: 12.9,
      transactionCount: 1650,
    },
    {
      channel: 'NHIA_HMO',
      label: 'NHIA / HMO Claims Remittance',
      amount: 2160000,
      formattedAmount: '₦2,160,000.00',
      percentage: 8.6,
      transactionCount: 480,
    },
  ],
  agingReceivables: [
    {
      bucket: '0-30 Days',
      amount: 1800000,
      formattedAmount: '₦1,800,000.00',
      invoiceCount: 42,
      riskLevel: 'LOW',
    },
    {
      bucket: '31-60 Days',
      amount: 850000,
      formattedAmount: '₦850,000.00',
      invoiceCount: 18,
      riskLevel: 'MEDIUM',
    },
    {
      bucket: '61-90 Days',
      amount: 380000,
      formattedAmount: '₦380,000.00',
      invoiceCount: 9,
      riskLevel: 'HIGH',
    },
    {
      bucket: '90+ Days',
      amount: 240000,
      formattedAmount: '₦240,000.00',
      invoiceCount: 6,
      riskLevel: 'CRITICAL',
    },
  ],
  dailyTrends: [
    { date: '2026-10-01', billed: 950000, collected: 840000 },
    { date: '2026-10-02', billed: 1020000, collected: 910000 },
    { date: '2026-10-03', billed: 880000, collected: 800000 },
    { date: '2026-10-04', billed: 640000, collected: 590000 },
    { date: '2026-10-05', billed: 1140000, collected: 1020000 },
    { date: '2026-10-06', billed: 1250000, collected: 1110000 },
    { date: '2026-10-07', billed: 980000, collected: 890000 },
  ],
};

export const INITIAL_CLINICAL_CENSUS: ClinicalCensusData = {
  period: 'THIS_MONTH',
  dateRange: {
    startDate: '2026-10-01',
    endDate: '2026-10-31',
  },
  totalHospitalBeds: 160,
  totalOccupiedBeds: 124,
  overallOccupancyRate: 77.5,
  averageLengthOfStayDays: 4.3,
  admissionsCount: 312,
  dischargesCount: 294,
  mortalityCount: 4,
  grossMortalityRate: 1.3,
  wards: [
    {
      wardId: 'WARD-MS-01',
      wardName: 'Male Surgical Ward',
      totalBeds: 32,
      occupiedBeds: 27,
      occupancyRate: 84.4,
      admissionsToday: 3,
      dischargesToday: 2,
      criticalPatients: 3,
    },
    {
      wardId: 'WARD-FM-02',
      wardName: 'Female Medical Ward',
      totalBeds: 34,
      occupiedBeds: 28,
      occupancyRate: 82.4,
      admissionsToday: 4,
      dischargesToday: 3,
      criticalPatients: 2,
    },
    {
      wardId: 'WARD-MAT-03',
      wardName: 'Maternity & Labour Ward',
      totalBeds: 28,
      occupiedBeds: 22,
      occupancyRate: 78.6,
      admissionsToday: 5,
      dischargesToday: 4,
      criticalPatients: 1,
    },
    {
      wardId: 'WARD-PICU-04',
      wardName: 'Pediatric ICU',
      totalBeds: 18,
      occupiedBeds: 13,
      occupancyRate: 72.2,
      admissionsToday: 2,
      dischargesToday: 1,
      criticalPatients: 4,
    },
    {
      wardId: 'WARD-AE-05',
      wardName: 'A&E Short-Stay Observation',
      totalBeds: 24,
      occupiedBeds: 21,
      occupancyRate: 87.5,
      admissionsToday: 8,
      dischargesToday: 6,
      criticalPatients: 5,
    },
    {
      wardId: 'WARD-PVT-06',
      wardName: 'Amenity Private Suites',
      totalBeds: 24,
      occupiedBeds: 13,
      occupancyRate: 54.2,
      admissionsToday: 1,
      dischargesToday: 2,
      criticalPatients: 0,
    },
  ],
  topMorbidity: [
    {
      icd10Code: 'B54',
      diagnosisName: 'Malaria, Unspecified (Severe & Uncomplicated)',
      caseCount: 382,
      percentage: 26.8,
      category: 'INFECTIOUS',
    },
    {
      icd10Code: 'I10',
      diagnosisName: 'Essential (Primary) Hypertension',
      caseCount: 246,
      percentage: 17.3,
      category: 'CHRONIC',
    },
    {
      icd10Code: 'A09',
      diagnosisName: 'Infectious Gastroenteritis & Colitis',
      caseCount: 188,
      percentage: 13.2,
      category: 'INFECTIOUS',
    },
    {
      icd10Code: 'J18.9',
      diagnosisName: 'Bronchopneumonia, Unspecified Organism',
      caseCount: 142,
      percentage: 10.0,
      category: 'INFECTIOUS',
    },
    {
      icd10Code: 'E11',
      diagnosisName: 'Type 2 Diabetes Mellitus with Complications',
      caseCount: 129,
      percentage: 9.1,
      category: 'CHRONIC',
    },
    {
      icd10Code: 'N39.0',
      diagnosisName: 'Urinary Tract Infection, Site Not Specified',
      caseCount: 98,
      percentage: 6.9,
      category: 'INFECTIOUS',
    },
    {
      icd10Code: 'O80',
      diagnosisName: 'Single Spontaneous Normal Delivery',
      caseCount: 84,
      percentage: 5.9,
      category: 'MATERNAL',
    },
    {
      icd10Code: 'S06',
      diagnosisName: 'Intracranial / Road Traffic Injury (Trauma)',
      caseCount: 62,
      percentage: 4.4,
      category: 'TRAUMA',
    },
    {
      icd10Code: 'K35',
      diagnosisName: 'Acute Appendicitis (Emergency Surgery)',
      caseCount: 48,
      percentage: 3.4,
      category: 'TRAUMA',
    },
    {
      icd10Code: 'R50.9',
      diagnosisName: 'Pyrexia of Unknown Origin',
      caseCount: 44,
      percentage: 3.0,
      category: 'OTHER',
    },
  ],
  admissionTrends: [
    { date: '2026-10-01', admissions: 14, discharges: 11 },
    { date: '2026-10-02', admissions: 16, discharges: 13 },
    { date: '2026-10-03', admissions: 12, discharges: 10 },
    { date: '2026-10-04', admissions: 9, discharges: 8 },
    { date: '2026-10-05', admissions: 18, discharges: 15 },
    { date: '2026-10-06', admissions: 15, discharges: 14 },
    { date: '2026-10-07', admissions: 13, discharges: 12 },
  ],
};

export const INITIAL_OPERATIONAL_METRICS: OperationalMetricsData = {
  period: 'THIS_MONTH',
  dateRange: {
    startDate: '2026-10-01',
    endDate: '2026-10-31',
  },
  dailyPatientFootfall: 420,
  newRegistrations: 110,
  returnVisits: 310,
  bedTurnoverRate: 1.95,
  satisfactionScore: 91.4,
  turnaroundTimes: [
    {
      department: 'GOPD',
      label: 'General Outpatient Clinic',
      metricName: 'Triage to Doctor Consultation',
      targetMinutes: 30,
      actualAverageMinutes: 24,
      status: 'NORMAL',
      sampleSize: 1840,
    },
    {
      department: 'LABORATORY',
      label: 'Clinical Diagnostic Lab',
      metricName: 'Specimen Intake to Result Release',
      targetMinutes: 45,
      actualAverageMinutes: 36,
      status: 'EXCELLENT',
      sampleSize: 3120,
    },
    {
      department: 'PHARMACY',
      label: 'Outpatient Pharmacy Dispensary',
      metricName: 'Prescription Queue to Dispense',
      targetMinutes: 20,
      actualAverageMinutes: 16,
      status: 'EXCELLENT',
      sampleSize: 2840,
    },
    {
      department: 'RADIOLOGY',
      label: 'Radiology Modalities & X-Ray',
      metricName: 'Image Acquisition to Radiologist Report',
      targetMinutes: 60,
      actualAverageMinutes: 74,
      status: 'DELAYED',
      sampleSize: 520,
    },
    {
      department: 'EMERGENCY',
      label: 'Accident & Emergency',
      metricName: 'Door-to-Bed Emergency Triage',
      targetMinutes: 10,
      actualAverageMinutes: 6,
      status: 'EXCELLENT',
      sampleSize: 410,
    },
  ],
  activityVolumes: [
    {
      cadre: 'Consultant Doctors',
      metric: 'Clinical Consultations Completed',
      totalCount: 1840,
      periodChangePercent: 8.5,
    },
    {
      cadre: 'Registered Nurses',
      metric: 'Shift Handover Endorsements',
      totalCount: 420,
      periodChangePercent: 3.2,
    },
    {
      cadre: 'Surgical Teams',
      metric: 'Major & Minor Surgeries Conducted',
      totalCount: 78,
      periodChangePercent: 12.4,
    },
    {
      cadre: 'Medical Laboratory Scientists',
      metric: 'Diagnostic Panels Analyzed',
      totalCount: 3120,
      periodChangePercent: 6.8,
    },
    {
      cadre: 'Radiographers & Radiologists',
      metric: 'Imaging Studies Verified',
      totalCount: 520,
      periodChangePercent: 4.1,
    },
  ],
};
