import { Appointment, AvailabilitySlot, Doctor } from "./types";

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "doc-001",
    name: "Dr. Babatunde Alabi",
    title: "Chief Consultant Cardiologist",
    specialty: "Cardiology",
    department: "Internal Medicine",
    roomNumber: "Consulting Room 102",
    phone: "+234 803 111 2233",
    email: "babatunde.alabi@hospital.gov.ng",
    maxPatientsPerSlot: 1,
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: "doc-002",
    name: "Dr. Chioma Okonjo",
    title: "Senior Consultant Obstetrician & Gynaecologist",
    specialty: "Obstetrics & Gynaecology",
    department: "Maternity & O&G",
    roomNumber: "Consulting Room 204",
    phone: "+234 802 333 4455",
    email: "chioma.okonjo@hospital.gov.ng",
    maxPatientsPerSlot: 1,
    availableDays: ["Monday", "Tuesday", "Thursday"],
  },
  {
    id: "doc-003",
    name: "Dr. Emeka Nnamdi",
    title: "Consultant Paediatrician",
    specialty: "Paediatrics",
    department: "Paediatrics & Child Health",
    roomNumber: "Consulting Room 108",
    phone: "+234 805 777 8899",
    email: "emeka.nnamdi@hospital.gov.ng",
    maxPatientsPerSlot: 1,
    availableDays: ["Tuesday", "Wednesday", "Friday"],
  },
  {
    id: "doc-004",
    name: "Dr. Aisha Bello",
    title: "Consultant Orthopaedic Surgeon",
    specialty: "Orthopaedics",
    department: "Surgical Services",
    roomNumber: "Consulting Room 301",
    phone: "+234 809 444 5566",
    email: "aisha.bello@hospital.gov.ng",
    maxPatientsPerSlot: 1,
    availableDays: ["Monday", "Thursday"],
  },
  {
    id: "doc-005",
    name: "Dr. Funmilayo Adeleke",
    title: "Consultant Physician & Nephrologist",
    specialty: "Nephrology",
    department: "Internal Medicine",
    roomNumber: "Consulting Room 105",
    phone: "+234 806 222 3344",
    email: "funmilayo.adeleke@hospital.gov.ng",
    maxPatientsPerSlot: 1,
    availableDays: ["Wednesday", "Thursday", "Saturday"],
  },
  {
    id: "doc-006",
    name: "Dr. Samuel Oladipo",
    title: "GOPD Medical Officer on Duty",
    specialty: "Family Medicine & General Practice",
    department: "General Outpatient (GOPD)",
    roomNumber: "GOPD Triage Clinic A",
    phone: "+234 807 555 6677",
    email: "samuel.oladipo@hospital.gov.ng",
    maxPatientsPerSlot: 4,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  },
];

export const MOCK_SLOTS: AvailabilitySlot[] = [
  // Dr. Babatunde Alabi slots
  {
    id: "slot-001",
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    date: "2026-09-28",
    startTime: "09:00",
    endTime: "09:30",
    status: "BOOKED",
    maxCapacity: 1,
    currentBookings: 1,
    clinicRoom: "Room 102",
  },
  {
    id: "slot-002",
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    date: "2026-09-28",
    startTime: "09:30",
    endTime: "10:00",
    status: "BOOKED",
    maxCapacity: 1,
    currentBookings: 1,
    clinicRoom: "Room 102",
  },
  {
    id: "slot-003",
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    date: "2026-09-28",
    startTime: "10:00",
    endTime: "10:30",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 102",
  },
  {
    id: "slot-004",
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    date: "2026-09-28",
    startTime: "11:00",
    endTime: "11:30",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 102",
  },
  {
    id: "slot-005",
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    date: "2026-09-28",
    startTime: "11:30",
    endTime: "12:00",
    status: "BLOCKED",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 102",
  },
  // Dr. Chioma Okonjo slots
  {
    id: "slot-006",
    doctorId: "doc-002",
    doctorName: "Dr. Chioma Okonjo",
    date: "2026-09-28",
    startTime: "09:00",
    endTime: "09:30",
    status: "BOOKED",
    maxCapacity: 1,
    currentBookings: 1,
    clinicRoom: "Room 204",
  },
  {
    id: "slot-007",
    doctorId: "doc-002",
    doctorName: "Dr. Chioma Okonjo",
    date: "2026-09-28",
    startTime: "10:00",
    endTime: "10:30",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 204",
  },
  {
    id: "slot-008",
    doctorId: "doc-002",
    doctorName: "Dr. Chioma Okonjo",
    date: "2026-09-28",
    startTime: "11:30",
    endTime: "12:00",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 204",
  },
  // Dr. Emeka Nnamdi slots
  {
    id: "slot-009",
    doctorId: "doc-003",
    doctorName: "Dr. Emeka Nnamdi",
    date: "2026-09-28",
    startTime: "13:00",
    endTime: "13:30",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 108",
  },
  {
    id: "slot-010",
    doctorId: "doc-003",
    doctorName: "Dr. Emeka Nnamdi",
    date: "2026-09-28",
    startTime: "13:30",
    endTime: "14:00",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 108",
  },
  // Dr. Aisha Bello slots
  {
    id: "slot-011",
    doctorId: "doc-004",
    doctorName: "Dr. Aisha Bello",
    date: "2026-09-28",
    startTime: "10:30",
    endTime: "11:00",
    status: "BOOKED",
    maxCapacity: 1,
    currentBookings: 1,
    clinicRoom: "Room 301",
  },
  {
    id: "slot-012",
    doctorId: "doc-004",
    doctorName: "Dr. Aisha Bello",
    date: "2026-09-28",
    startTime: "11:00",
    endTime: "11:30",
    status: "AVAILABLE",
    maxCapacity: 1,
    currentBookings: 0,
    clinicRoom: "Room 301",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "apt-001",
    appointmentNumber: "APT-2026-0081",
    patientId: "pat-001",
    patientMrn: "MRN-2026-0001",
    patientName: "Amina Yusuf",
    patientPhone: "+234 803 234 5678",
    patientGender: "Female",
    patientAge: 34,
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    specialty: "Cardiology",
    department: "Internal Medicine",
    slotId: "slot-001",
    date: "2026-09-28",
    startTime: "09:00",
    endTime: "09:30",
    type: "FOLLOW_UP",
    status: "CHECKED_IN",
    queueType: "SCHEDULED_APPOINTMENT",
    priority: "ROUTINE",
    reasonForVisit: "Post-hypertension titration review, baseline lipid panel review",
    clinicalNotes: "Patient arrived on time. BP taken at triage: 135/88 mmHg. Awaiting doctor entry.",
    reminderPreference: "BOTH",
    reminderStatus: "DELIVERED",
    reminderSentAt: "2026-09-27T08:00:00Z",
    checkInTime: "2026-09-28T08:45:00Z",
    createdAt: "2026-09-20T10:15:00Z",
    updatedAt: "2026-09-28T08:45:00Z",
  },
  {
    id: "apt-002",
    appointmentNumber: "APT-2026-0082",
    patientId: "pat-002",
    patientMrn: "MRN-2026-0002",
    patientName: "Chukwudi Eze",
    patientPhone: "+234 802 987 6543",
    patientGender: "Male",
    patientAge: 45,
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    specialty: "Cardiology",
    department: "Internal Medicine",
    slotId: "slot-002",
    date: "2026-09-28",
    startTime: "09:30",
    endTime: "10:00",
    type: "CONSULTATION",
    status: "SCHEDULED",
    queueType: "SCHEDULED_APPOINTMENT",
    priority: "ROUTINE",
    reasonForVisit: "Exertional chest tightness, ECG findings referred from peripheral clinic",
    clinicalNotes: "Referral letter attached in Medical Records.",
    reminderPreference: "SMS",
    reminderStatus: "SENT",
    reminderSentAt: "2026-09-27T08:30:00Z",
    createdAt: "2026-09-21T14:20:00Z",
    updatedAt: "2026-09-27T08:30:00Z",
  },
  {
    id: "apt-003",
    appointmentNumber: "APT-2026-0083",
    patientId: "pat-003",
    patientMrn: "MRN-2026-0003",
    patientName: "Fatima Ibrahim",
    patientPhone: "+234 814 555 7890",
    patientGender: "Female",
    patientAge: 29,
    doctorId: "doc-002",
    doctorName: "Dr. Chioma Okonjo",
    specialty: "Obstetrics & Gynaecology",
    department: "Maternity & O&G",
    slotId: "slot-006",
    date: "2026-09-28",
    startTime: "09:00",
    endTime: "09:30",
    type: "SPECIALIST_CLINIC",
    status: "IN_CONSULTATION",
    queueType: "SCHEDULED_APPOINTMENT",
    priority: "PRIORITY",
    reasonForVisit: "Antenatal high-risk clinic, gestational diabetes screening check",
    clinicalNotes: "OGTT results normal. Fetal heart rate 142 bpm. Doctor currently examining.",
    reminderPreference: "BOTH",
    reminderStatus: "DELIVERED",
    reminderSentAt: "2026-09-27T08:00:00Z",
    checkInTime: "2026-09-28T08:50:00Z",
    createdAt: "2026-09-18T11:00:00Z",
    updatedAt: "2026-09-28T09:05:00Z",
  },
  {
    id: "apt-004",
    appointmentNumber: "APT-2026-0084",
    patientId: "pat-004",
    patientMrn: "MRN-2026-0004",
    patientName: "Oluwaseun Adeleke",
    patientPhone: "+234 809 112 2334",
    patientGender: "Male",
    patientAge: 52,
    doctorId: "doc-004",
    doctorName: "Dr. Aisha Bello",
    specialty: "Orthopaedics",
    department: "Surgical Services",
    slotId: "slot-011",
    date: "2026-09-28",
    startTime: "10:30",
    endTime: "11:00",
    type: "PRE_OP_REVIEW",
    status: "SCHEDULED",
    queueType: "SCHEDULED_APPOINTMENT",
    priority: "URGENT",
    reasonForVisit: "Pre-operative evaluation for right total hip arthroplasty",
    reminderPreference: "EMAIL",
    reminderStatus: "DELIVERED",
    reminderSentAt: "2026-09-27T09:00:00Z",
    createdAt: "2026-09-15T09:30:00Z",
    updatedAt: "2026-09-27T09:00:00Z",
  },
  {
    id: "apt-005",
    appointmentNumber: "APT-2026-0075",
    patientId: "pat-005",
    patientMrn: "MRN-2026-0005",
    patientName: "Ngozi Obi",
    patientPhone: "+234 818 666 4321",
    patientGender: "Female",
    patientAge: 61,
    doctorId: "doc-001",
    doctorName: "Dr. Babatunde Alabi",
    specialty: "Cardiology",
    department: "Internal Medicine",
    slotId: "slot-003",
    date: "2026-09-26",
    startTime: "10:00",
    endTime: "10:30",
    type: "FOLLOW_UP",
    status: "COMPLETED",
    queueType: "SCHEDULED_APPOINTMENT",
    priority: "ROUTINE",
    reasonForVisit: "Holter monitor evaluation",
    clinicalNotes: "Sinus rhythm confirmed. Continue current dose of Bisoprolol 5mg daily. Next review in 3 months.",
    reminderPreference: "SMS",
    reminderStatus: "DELIVERED",
    reminderSentAt: "2026-09-25T08:00:00Z",
    checkInTime: "2026-09-26T09:45:00Z",
    createdAt: "2026-09-12T16:00:00Z",
    updatedAt: "2026-09-26T10:40:00Z",
  },
  // FR-AP-05: Specific GOPD Walk-in entries to demonstrate distinction from scheduled specialist appointments
  {
    id: "apt-walkin-001",
    appointmentNumber: "GOPD-2026-W012",
    patientId: "pat-006",
    patientMrn: "MRN-2026-0008",
    patientName: "Musa Danjuma",
    patientPhone: "+234 803 777 9900",
    patientGender: "Male",
    patientAge: 27,
    doctorId: "doc-006",
    doctorName: "Dr. Samuel Oladipo",
    specialty: "Family Medicine & General Practice",
    department: "General Outpatient (GOPD)",
    slotId: "slot-walkin",
    date: "2026-09-28",
    startTime: "08:15",
    endTime: "08:30",
    type: "CONSULTATION",
    status: "CHECKED_IN",
    queueType: "GOPD_WALK_IN", // Per FR-AP-05
    priority: "ROUTINE",
    reasonForVisit: "Walk-in acute headache and general malaise x 2 days",
    clinicalNotes: "Assigned token #12 in General Outpatient walk-in queue. Vitals taken.",
    reminderPreference: "NONE",
    reminderStatus: "PENDING",
    checkInTime: "2026-09-28T08:15:00Z",
    createdAt: "2026-09-28T08:15:00Z",
    updatedAt: "2026-09-28T08:15:00Z",
  },
  {
    id: "apt-walkin-002",
    appointmentNumber: "GOPD-2026-W013",
    patientId: "pat-007",
    patientMrn: "MRN-2026-0011",
    patientName: "Grace Bassey",
    patientPhone: "+234 802 444 8877",
    patientGender: "Female",
    patientAge: 19,
    doctorId: "doc-006",
    doctorName: "Dr. Samuel Oladipo",
    specialty: "Family Medicine & General Practice",
    department: "General Outpatient (GOPD)",
    slotId: "slot-walkin",
    date: "2026-09-28",
    startTime: "08:40",
    endTime: "08:55",
    type: "CONSULTATION",
    status: "CHECKED_IN",
    queueType: "GOPD_WALK_IN", // Per FR-AP-05
    priority: "URGENT",
    reasonForVisit: "High-grade fever (39.1C) with severe chills",
    clinicalNotes: "Assigned token #13 in GOPD triage queue. Fast-tracked for malaria RDT & urgent consult.",
    reminderPreference: "NONE",
    reminderStatus: "PENDING",
    checkInTime: "2026-09-28T08:40:00Z",
    createdAt: "2026-09-28T08:40:00Z",
    updatedAt: "2026-09-28T08:40:00Z",
  },
];

export const MOCK_SEARCH_PATIENTS = [
  {
    id: "pat-001",
    mrn: "MRN-2026-0001",
    firstName: "Amina",
    lastName: "Yusuf",
    gender: "Female" as const,
    age: 34,
    phone: "+234 803 234 5678",
  },
  {
    id: "pat-002",
    mrn: "MRN-2026-0002",
    firstName: "Chukwudi",
    lastName: "Eze",
    gender: "Male" as const,
    age: 45,
    phone: "+234 802 987 6543",
  },
  {
    id: "pat-003",
    mrn: "MRN-2026-0003",
    firstName: "Fatima",
    lastName: "Ibrahim",
    gender: "Female" as const,
    age: 29,
    phone: "+234 814 555 7890",
  },
  {
    id: "pat-004",
    mrn: "MRN-2026-0004",
    firstName: "Oluwaseun",
    lastName: "Adeleke",
    gender: "Male" as const,
    age: 52,
    phone: "+234 809 112 2334",
  },
  {
    id: "pat-005",
    mrn: "MRN-2026-0005",
    firstName: "Ngozi",
    lastName: "Obi",
    gender: "Female" as const,
    age: 61,
    phone: "+234 818 666 4321",
  },
];
