import { SurgeryBooking } from "./types";

export const initialSurgeryBookings: SurgeryBooking[] = [
  {
    id: "SURG-001",
    bookingNumber: "OR-2026-0081",
    patientId: "PAT-001",
    patientName: "Amina Yusuf",
    hospitalNumber: "HIMS-2026-00142",
    age: 28,
    gender: "Female",
    procedureName: "Emergency Caesarean Section",
    diagnosis: "Cephalopelvic Disproportion (CPD) in active labor",
    theatreRoom: "OR 3 - Emergency / Trauma",
    leadSurgeon: "Dr. Babatunde Alabi (Consultant Obstetrician)",
    anaesthetist: "Dr. K. Okafor (Anaesthetist)",
    scheduledStartTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    estimatedDurationMinutes: 60,
    priority: "EMERGENCY",
    status: "IN_THEATRE",
    preOpChecklist: {
      patientIdentified: true,
      siteMarked: true,
      consentConfirmed: true,
      anaesthesiaSafetyCheckComplete: true,
      pulseOximeterFunctioning: true,
      allergiesReviewed: true,
      airwayDifficultyAssessed: true,
      aspirationRiskAssessed: true,
      bloodLossRiskAssessed: true,
      adequateIvAccessVerified: true,
      completedBy: "Nurse Chinyere Okon",
      completedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: "SURG-002",
    bookingNumber: "OR-2026-0082",
    patientId: "PAT-002",
    patientName: "Emeka Chukwu",
    hospitalNumber: "HIMS-2026-00215",
    age: 64,
    gender: "Male",
    procedureName: "Total Hip Arthroplasty (Right)",
    diagnosis: "Severe Primary Osteoarthritis of Right Hip",
    theatreRoom: "OR 2 - Orthopaedic",
    leadSurgeon: "Dr. Femi Adeleke (Consultant Orthopaedic)",
    anaesthetist: "Dr. Aisha Danjuma",
    scheduledStartTime: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    estimatedDurationMinutes: 120,
    priority: "ELECTIVE",
    status: "PACU",
    preOpChecklist: {
      patientIdentified: true,
      siteMarked: true,
      consentConfirmed: true,
      anaesthesiaSafetyCheckComplete: true,
      pulseOximeterFunctioning: true,
      allergiesReviewed: true,
      airwayDifficultyAssessed: true,
      aspirationRiskAssessed: true,
      bloodLossRiskAssessed: true,
      adequateIvAccessVerified: true,
      completedBy: "Nurse Maryam Bello",
      completedAt: new Date(Date.now() - 160 * 60 * 1000).toISOString(),
    },
    intraOpNotes: {
      timeOutConfirmed: true,
      incisionTime: "08:15",
      closureTime: "10:10",
      leadSurgeon: "Dr. Femi Adeleke",
      assistantSurgeon: "Dr. O. Adelekan",
      anaesthetist: "Dr. Aisha Danjuma",
      scrubNurse: "Staff Nurse Joy",
      circulatingNurse: "Staff Nurse Danladi",
      procedurePerformed: "Uncemented Right Total Hip Replacement with ceramic-on-polyethylene bearing",
      surgicalFindings: "Extensive osteophytes, severe femoral head subchondral collapse, intact acetabular bone stock",
      estimatedBloodLossMl: 350,
      specimensCollected: true,
      specimenLabels: ["Femoral Head (Histopathology)"],
      spongeNeedleCountVerified: true,
      implantBatchNumbers: "Stryker Trident II Cup #45821, Accolade II Stem #99214",
      recordedBy: "Dr. Femi Adeleke",
      recordedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    pacuLog: {
      admissionTime: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      initialVitals: {
        bloodPressure: "128/82",
        pulseRate: 74,
        respiratoryRate: 16,
        oxygenSaturation: 98,
        temperature: 36.6,
        painScore: 3,
      },
      aldreteScore: {
        activity: 2,
        respiration: 2,
        circulation: 2,
        consciousness: 2,
        oxygenSaturation: 2,
        totalScore: 10,
      },
      analgesiaAdministered: "IV Paracetamol 1g + Tramadol 50mg PRN",
      ivFluidsAdministered: "Normal Saline 500ml @ 100ml/hr",
      recoveryNotes: "Patient awake, alert, moving upper extremities, spinal anaesthesia wearing off with sensation returning to toes.",
      fitForWardTransfer: true,
      authorizedBy: "Dr. Aisha Danjuma (Anaesthetist)",
      destinationWard: "Male Orthopaedic Ward (Ward B)",
    },
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: "SURG-003",
    bookingNumber: "OR-2026-0083",
    patientId: "PAT-003",
    patientName: "Fatima Ibrahim",
    hospitalNumber: "HIMS-2026-00389",
    age: 41,
    gender: "Female",
    procedureName: "Laparoscopic Cholecystectomy",
    diagnosis: "Symptomatic Cholelithiasis (Gallstones)",
    theatreRoom: "OR 4 - Laparoscopic & Endoscopy",
    leadSurgeon: "Dr. Mansur Sani (General Surgeon)",
    anaesthetist: "Dr. K. Okafor",
    scheduledStartTime: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    estimatedDurationMinutes: 75,
    priority: "ELECTIVE",
    status: "PRE_OP",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SURG-004",
    bookingNumber: "OR-2026-0084",
    patientId: "PAT-004",
    patientName: "Oluwaseun Balogun",
    hospitalNumber: "HIMS-2026-00412",
    age: 33,
    gender: "Male",
    procedureName: "Exploratory Laparotomy",
    diagnosis: "Blunt Abdominal Trauma with Peritoneal Signs",
    theatreRoom: "OR 1 - General Surgery",
    leadSurgeon: "Dr. T. Ogunlesi (Consultant Surgeon)",
    anaesthetist: "Dr. Aisha Danjuma",
    scheduledStartTime: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    estimatedDurationMinutes: 90,
    priority: "URGENT",
    status: "SCHEDULED",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SURG-005",
    bookingNumber: "OR-2026-0078",
    patientId: "PAT-005",
    patientName: "Grace Eze",
    hospitalNumber: "HIMS-2026-00095",
    age: 22,
    gender: "Female",
    procedureName: "Emergency Open Appendectomy",
    diagnosis: "Acute Suppurative Appendicitis with localized peritonitis",
    theatreRoom: "OR 3 - Emergency / Trauma",
    leadSurgeon: "Dr. Mansur Sani",
    anaesthetist: "Dr. K. Okafor",
    scheduledStartTime: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
    estimatedDurationMinutes: 50,
    priority: "EMERGENCY",
    status: "COMPLETED",
    preOpChecklist: {
      patientIdentified: true,
      siteMarked: true,
      consentConfirmed: true,
      anaesthesiaSafetyCheckComplete: true,
      pulseOximeterFunctioning: true,
      allergiesReviewed: true,
      airwayDifficultyAssessed: true,
      aspirationRiskAssessed: true,
      bloodLossRiskAssessed: true,
      adequateIvAccessVerified: true,
      completedBy: "Nurse Joy",
      completedAt: new Date(Date.now() - 370 * 60 * 1000).toISOString(),
    },
    intraOpNotes: {
      timeOutConfirmed: true,
      incisionTime: "04:30",
      closureTime: "05:15",
      leadSurgeon: "Dr. Mansur Sani",
      anaesthetist: "Dr. K. Okafor",
      scrubNurse: "Staff Nurse Peter",
      circulatingNurse: "Staff Nurse Danladi",
      procedurePerformed: "Standard gridiron appendectomy with mesoappendix ligation and purse-string inversion",
      surgicalFindings: "Inflamed, turgid appendix measuring 9cm, no perforation, minimal turbid exudate in right iliac fossa",
      estimatedBloodLossMl: 40,
      specimensCollected: true,
      specimenLabels: ["Vermiform Appendix (Histopathology)"],
      spongeNeedleCountVerified: true,
      recordedBy: "Dr. Mansur Sani",
      recordedAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    },
    pacuLog: {
      admissionTime: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
      initialVitals: {
        bloodPressure: "115/75",
        pulseRate: 80,
        respiratoryRate: 18,
        oxygenSaturation: 99,
        temperature: 37.0,
        painScore: 2,
      },
      aldreteScore: {
        activity: 2,
        respiration: 2,
        circulation: 2,
        consciousness: 2,
        oxygenSaturation: 2,
        totalScore: 10,
      },
      recoveryNotes: "Smooth PACU recovery, vitals stable, wound dressing dry and intact. Transferred to Female Surgical Ward.",
      fitForWardTransfer: true,
      authorizedBy: "Dr. K. Okafor",
      destinationWard: "Female Surgical Ward (Ward C)",
      transferTime: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    },
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
  },
];
