import { GopdPatient } from "./types";

export const MOCK_QUEUE: GopdPatient[] = [
  {
    id: "gopd_01",
    patientId: "pat_01",
    patientName: "Adekunle Ibrahim",
    hospitalNumber: "HIMS-2026-0001",
    age: 45,
    gender: "Male",
    status: "WAITING_TRIAGE",
    triagePriority: "STANDARD",
    queueNumber: "G-001",
    registeredAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: "gopd_02",
    patientId: "pat_02",
    patientName: "Chioma Okonkwo",
    hospitalNumber: "HIMS-2026-0002",
    age: 29,
    gender: "Female",
    status: "WAITING_TRIAGE",
    triagePriority: "URGENT",
    queueNumber: "G-002",
    registeredAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "gopd_03",
    patientId: "pat_03",
    patientName: "Babajide Adeleke",
    hospitalNumber: "HIMS-2026-0003",
    age: 58,
    gender: "Male",
    status: "WAITING_DOCTOR",
    triagePriority: "URGENT",
    queueNumber: "G-003",
    registeredAt: new Date(Date.now() - 45 * 60000).toISOString(),
    vitals: {
      bloodPressure: "155/95",
      systolic: 155,
      diastolic: 95,
      pulseRate: 92,
      temperature: 38.6,
      spO2: 95,
      respiratoryRate: 22,
      weight: 82,
      height: 174,
      bmi: 27.1,
      painScore: 4,
      consciousnessLevel: "Alert",
      triageNotes: "High grade fever for 3 days with intense frontal headache and shivering.",
      recordedBy: "Nurse B. Taiwo, RN",
      recordedAt: new Date(Date.now() - 30 * 60000).toISOString()
    }
  },
  {
    id: "gopd_04",
    patientId: "pat_04",
    patientName: "Fatima Garba",
    hospitalNumber: "HIMS-2026-0004",
    age: 34,
    gender: "Female",
    status: "WAITING_DOCTOR",
    triagePriority: "STANDARD",
    queueNumber: "G-004",
    registeredAt: new Date(Date.now() - 60 * 60000).toISOString(),
    vitals: {
      bloodPressure: "118/78",
      systolic: 118,
      diastolic: 78,
      pulseRate: 74,
      temperature: 36.7,
      spO2: 99,
      respiratoryRate: 16,
      weight: 62,
      height: 160,
      bmi: 24.2,
      painScore: 2,
      consciousnessLevel: "Alert",
      triageNotes: "Routine walk-in for refill and non-productive cough.",
      recordedBy: "Nurse B. Taiwo, RN",
      recordedAt: new Date(Date.now() - 40 * 60000).toISOString()
    }
  },
  {
    id: "gopd_05",
    patientId: "pat_05",
    patientName: "Emeka Eze",
    hospitalNumber: "HIMS-2026-0005",
    age: 67,
    gender: "Male",
    status: "WAITING_DOCTOR",
    triagePriority: "EMERGENCY",
    queueNumber: "G-005",
    registeredAt: new Date(Date.now() - 10 * 60000).toISOString(),
    vitals: {
      bloodPressure: "185/110",
      systolic: 185,
      diastolic: 110,
      pulseRate: 112,
      temperature: 37.1,
      spO2: 92,
      respiratoryRate: 26,
      weight: 90,
      height: 172,
      bmi: 30.4,
      painScore: 6,
      consciousnessLevel: "Alert",
      triageNotes: "Acute substernal chest tightness and diaphoresis. Prioritize immediately.",
      recordedBy: "Nurse C. Musa, RN",
      recordedAt: new Date(Date.now() - 5 * 60000).toISOString()
    }
  },
  {
    id: "gopd_06",
    patientId: "pat_06",
    patientName: "Grace Danjuma",
    hospitalNumber: "HIMS-2026-0006",
    age: 22,
    gender: "Female",
    status: "COMPLETED",
    triagePriority: "STANDARD",
    queueNumber: "G-006",
    registeredAt: new Date(Date.now() - 120 * 60000).toISOString(),
    vitals: {
      bloodPressure: "110/70",
      systolic: 110,
      diastolic: 70,
      pulseRate: 68,
      temperature: 36.5,
      spO2: 99,
      respiratoryRate: 15,
      weight: 55,
      height: 165,
      bmi: 20.2,
      consciousnessLevel: "Alert",
      recordedBy: "Nurse B. Taiwo, RN",
      recordedAt: new Date(Date.now() - 110 * 60000).toISOString()
    },
    consultation: {
      id: "cons_01",
      gopdPatientId: "gopd_06",
      doctorId: "doc_01",
      doctorName: "Dr. K. Bello, FWACS",
      chiefComplaint: "Painful sore throat and difficulty swallowing for 2 days.",
      historyOfPresentingIllness: "Onset was sudden with fever and tender cervical lymph nodes.",
      physicalExamination: "Erythematous tonsils with purulent exudates bilaterally. No stridor.",
      diagnoses: [
        {
          icd10Code: "J02.9",
          description: "Acute pharyngitis, unspecified",
          type: "PRIMARY"
        }
      ],
      notes: "Started on oral amoxicillin-clavulanate. Advised warm saline gargles.",
      disposition: "DISCHARGED",
      createdAt: new Date(Date.now() - 70 * 60000).toISOString()
    }
  }
];
