import {
  Account,
  CashBankTransaction,
  JournalVoucher,
  ReconciliationItem,
} from "./types";

export const INITIAL_CHART_OF_ACCOUNTS: Account[] = [
  // --- ASSETS (1000 - 1999) ---
  {
    id: "acc-1010",
    code: "1010",
    name: "Cash in Hand - Central Hospital Cashier",
    type: "ASSET",
    description: "Physical cash collections at billing and outpatient cash points",
    balance: 2450000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-1020",
    code: "1020",
    name: "Treasury Single Account (TSA) - CBN",
    type: "ASSET",
    description: "Central Bank of Nigeria designated operating account for hospital IGR",
    balance: 84250000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-1030",
    code: "1030",
    name: "Commercial Bank Revolving Account",
    type: "ASSET",
    description: "Commercial bank sub-account for POS terminals and automated sweeps",
    balance: 14600000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-1100",
    code: "1100",
    name: "Patient Accounts Receivable",
    type: "ASSET",
    description: "Unpaid patient and HMO/NHIA insurance invoices",
    balance: 9350000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-1200",
    code: "1200",
    name: "Pharmacy Inventory Asset",
    type: "ASSET",
    description: "Valuation of pharmaceutical drugs in central store and dispensaries",
    balance: 38200000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-1500",
    code: "1500",
    name: "Medical Diagnostic Equipment",
    type: "ASSET",
    description: "Hospital MRI, CT scan, ventilators, and surgical apparatus",
    balance: 215000000,
    currency: "NGN",
    isActive: true,
  },

  // --- LIABILITIES (2000 - 2999) ---
  {
    id: "acc-2010",
    code: "2010",
    name: "Accounts Payable - Drug Suppliers",
    type: "LIABILITY",
    description: "Outstanding invoices due to pharmaceutical and consumables vendors",
    balance: 18400000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-2020",
    code: "2020",
    name: "Patient Admission Advance Deposits",
    type: "LIABILITY",
    description: "Cautionary deposits collected from patients awaiting discharge reconciliation",
    balance: 4850000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-2030",
    code: "2030",
    name: "Accrued Staff Remuneration",
    type: "LIABILITY",
    description: "Payable call-duty allowances, locum fees, and shift benefits",
    balance: 12500000,
    currency: "NGN",
    isActive: true,
  },

  // --- EQUITY (3000 - 3999) ---
  {
    id: "acc-3010",
    code: "3010",
    name: "Federal Government Capital Subvention",
    type: "EQUITY",
    description: "Federal Ministry of Health developmental capital and subventions",
    balance: 250000000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-3020",
    code: "3020",
    name: "Accumulated Hospital Operating Surplus",
    type: "EQUITY",
    description: "Cumulative retained surplus from internal generated revenue (IGR)",
    balance: 56100000,
    currency: "NGN",
    isActive: true,
  },

  // --- REVENUE (4000 - 4999) ---
  {
    id: "acc-4010",
    code: "4010",
    name: "Patient Consultation Fees Revenue",
    type: "REVENUE",
    description: "Outpatient and specialist clinical consultation receipts",
    balance: 8900000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-4020",
    code: "4020",
    name: "Inpatient Bed & Nursing Accommodation Revenue",
    type: "REVENUE",
    description: "Ward admission charges, per-diem accommodation, and nursing care fees",
    balance: 16400000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-4030",
    code: "4030",
    name: "Pharmacy Prescription Sales Revenue",
    type: "REVENUE",
    description: "Dispensary sales for ethical formulations and OTC pharmaceuticals",
    balance: 24750000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-4040",
    code: "4040",
    name: "Laboratory Investigations Revenue",
    type: "REVENUE",
    description: "Haematology, microbiology, and clinical chemistry laboratory tariffs",
    balance: 11200000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-4050",
    code: "4050",
    name: "Surgical Theatre & Procedure Revenue",
    type: "REVENUE",
    description: "Major, intermediate, and minor surgical theatre facility fees",
    balance: 14800000,
    currency: "NGN",
    isActive: true,
  },

  // --- EXPENSES (5000 - 5999) ---
  {
    id: "acc-5010",
    code: "5010",
    name: "Clinical Drugs & Consumables Cost",
    type: "EXPENSE",
    description: "Direct cost of pharmaceutical formulations dispensed to patients",
    balance: 17300000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-5020",
    code: "5020",
    name: "Clinical Staff Call-duty & Locum Allowances",
    type: "EXPENSE",
    description: "Physician, nursing, and pharmacist call duty stipends",
    balance: 14200000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-5030",
    code: "5030",
    name: "Hospital Power, Generator Diesel & Utilities",
    type: "EXPENSE",
    description: "Continuous power backup diesel, water treatment, and public utilities",
    balance: 8650000,
    currency: "NGN",
    isActive: true,
  },
  {
    id: "acc-5040",
    code: "5040",
    name: "Diagnostic & Bio-medical Equipment Maintenance",
    type: "EXPENSE",
    description: "Preventative servicing and calibration contracts for clinical hardware",
    balance: 4950000,
    currency: "NGN",
    isActive: true,
  },
];

export const INITIAL_JOURNAL_VOUCHERS: JournalVoucher[] = [
  {
    id: "jv-001",
    voucherNumber: "JV-2026-0041",
    date: "2026-09-27",
    referenceNumber: "BILLING-BATCH-20260927-01",
    description: "Daily consolidation of Outpatient & Pharmacy Billing receipts to TSA account",
    items: [
      {
        id: "jvi-1",
        accountId: "acc-1020",
        accountCode: "1020",
        accountName: "Treasury Single Account (TSA) - CBN",
        debit: 1850000,
        credit: 0,
        memo: "Direct lodgement of daily cashier collections",
      },
      {
        id: "jvi-2",
        accountId: "acc-4010",
        accountCode: "4010",
        accountName: "Patient Consultation Fees Revenue",
        debit: 0,
        credit: 650000,
        memo: "GOPD and specialist clinic consultation fees",
      },
      {
        id: "jvi-3",
        accountId: "acc-4030",
        accountCode: "4030",
        accountName: "Pharmacy Prescription Sales Revenue",
        debit: 0,
        credit: 1200000,
        memo: "Outpatient dispensary pharmaceuticals revenue",
      },
    ],
    totalDebit: 1850000,
    totalCredit: 1850000,
    status: "POSTED",
    preparedBy: "Musa Ibrahim",
    preparedByRole: "ACCOUNTANT",
    approvedBy: "Mrs. Nkechi Okafor",
    approvedByRole: "CHIEF_ACCOUNTANT",
    approvedAt: "2026-09-27T17:30:00Z",
    createdAt: "2026-09-27T16:00:00Z",
    updatedAt: "2026-09-27T17:30:00Z",
  },
  {
    id: "jv-002",
    voucherNumber: "JV-2026-0042",
    date: "2026-09-28",
    referenceNumber: "INV-DISCHARGE-BATCH-0928",
    description: "Consolidated Inpatient Bed & Nursing care revenue recognition from Ward Discharges",
    items: [
      {
        id: "jvi-4",
        accountId: "acc-1100",
        accountCode: "1100",
        accountName: "Patient Accounts Receivable",
        debit: 920000,
        credit: 0,
        memo: "Invoiced discharge charges awaiting payment",
      },
      {
        id: "jvi-5",
        accountId: "acc-4020",
        accountCode: "4020",
        accountName: "Inpatient Bed & Nursing Accommodation Revenue",
        debit: 0,
        credit: 920000,
        memo: "Earned ward accommodation and nursing care",
      },
    ],
    totalDebit: 920000,
    totalCredit: 920000,
    status: "APPROVED",
    preparedBy: "Musa Ibrahim",
    preparedByRole: "ACCOUNTANT",
    approvedBy: "Mrs. Nkechi Okafor",
    approvedByRole: "CHIEF_ACCOUNTANT",
    approvedAt: "2026-09-28T11:00:00Z",
    createdAt: "2026-09-28T09:45:00Z",
    updatedAt: "2026-09-28T11:00:00Z",
  },
  {
    id: "jv-003",
    voucherNumber: "JV-2026-0043",
    date: "2026-09-28",
    referenceNumber: "PO-DIESEL-GEN-20260928",
    description: "Generator backup fuel disbursement for Main Hospital Sub-Station",
    items: [
      {
        id: "jvi-6",
        accountId: "acc-5030",
        accountCode: "5030",
        accountName: "Hospital Power, Generator Diesel & Utilities",
        debit: 750000,
        credit: 0,
        memo: "5,000 litres automated fuel supply delivery",
      },
      {
        id: "jvi-7",
        accountId: "acc-1030",
        accountCode: "1030",
        accountName: "Commercial Bank Revolving Account",
        debit: 0,
        credit: 750000,
        memo: "Direct bank transfer payment to NNPC partner depot",
      },
    ],
    totalDebit: 750000,
    totalCredit: 750000,
    status: "PENDING_APPROVAL",
    preparedBy: "Tariq Danladi",
    preparedByRole: "ACCOUNTANT",
    createdAt: "2026-09-28T13:10:00Z",
    updatedAt: "2026-09-28T13:10:00Z",
  },
];

export const INITIAL_CASH_BANK_TRANSACTIONS: CashBankTransaction[] = [
  {
    id: "cbt-001",
    transactionNumber: "CBT-2026-0121",
    date: "2026-09-28",
    type: "RECEIPT",
    bankAccountId: "acc-1020",
    bankAccountName: "Treasury Single Account (TSA) - CBN",
    contraAccountId: "acc-4010",
    contraAccountName: "Patient Consultation Fees Revenue",
    amount: 125000,
    description: "POS settlement for Specialist Cardiology & Antenatal clinic collections",
    paymentMethod: "POS",
    referenceNumber: "POS-REF-9921448",
    status: "CLEARED",
    reconciledWithBillingId: "rcpt-001",
    recordedBy: "Central Cashier Desk",
    createdAt: "2026-09-28T10:15:00Z",
  },
  {
    id: "cbt-002",
    transactionNumber: "CBT-2026-0122",
    date: "2026-09-28",
    type: "RECEIPT",
    bankAccountId: "acc-1010",
    bankAccountName: "Cash in Hand - Central Hospital Cashier",
    contraAccountId: "acc-4030",
    contraAccountName: "Pharmacy Prescription Sales Revenue",
    amount: 48500,
    description: "Cash payment for prescription drugs dispense #RX-2026-0042",
    paymentMethod: "CASH",
    referenceNumber: "RCPT-2026-0084",
    status: "RECONCILED",
    reconciledWithBillingId: "rcpt-002",
    recordedBy: "Pharmacy Cash Point A",
    createdAt: "2026-09-28T11:45:00Z",
  },
  {
    id: "cbt-003",
    transactionNumber: "CBT-2026-0123",
    date: "2026-09-28",
    type: "PAYMENT",
    bankAccountId: "acc-1030",
    bankAccountName: "Commercial Bank Revolving Account",
    contraAccountId: "acc-5030",
    contraAccountName: "Hospital Power, Generator Diesel & Utilities",
    amount: 750000,
    description: "Emergency generator diesel supply 5,000L",
    paymentMethod: "BANK_TRANSFER",
    referenceNumber: "NIBSS-TRF-8821990",
    status: "PENDING",
    recordedBy: "Treasury Officer",
    createdAt: "2026-09-28T13:20:00Z",
  },
];

// FR-GL-05: Realistic Reconciliation dataset against Billing's patient revenue
export const INITIAL_RECONCILIATION_ITEMS: ReconciliationItem[] = [
  {
    id: "recon-001",
    billingReceiptId: "rcpt-001",
    receiptNumber: "RCPT-2026-0001",
    invoiceNumber: "INV-2026-0001",
    patientMrn: "MRN-2026-0001",
    patientName: "Amina Yusuf",
    paymentMethod: "POS",
    billingAmount: 35000,
    glPostedAmount: 35000,
    glTransactionRef: "CBT-2026-0121",
    status: "MATCHED",
    varianceAmount: 0,
    transactionDate: "2026-09-28",
  },
  {
    id: "recon-002",
    billingReceiptId: "rcpt-002",
    receiptNumber: "RCPT-2026-0002",
    invoiceNumber: "INV-2026-0002",
    patientMrn: "MRN-2026-0002",
    patientName: "Chukwudi Eze",
    paymentMethod: "CASH",
    billingAmount: 48500,
    glPostedAmount: 48500,
    glTransactionRef: "CBT-2026-0122",
    status: "MATCHED",
    varianceAmount: 0,
    transactionDate: "2026-09-28",
  },
  {
    id: "recon-003",
    billingReceiptId: "rcpt-003",
    receiptNumber: "RCPT-2026-0003",
    invoiceNumber: "INV-2026-0003",
    patientMrn: "MRN-2026-0003",
    patientName: "Fatima Ibrahim",
    paymentMethod: "BANK_TRANSFER",
    billingAmount: 18500,
    glPostedAmount: 0,
    status: "UNPOSTED_IN_GL",
    varianceAmount: 18500,
    transactionDate: "2026-09-28",
  },
  {
    id: "recon-004",
    billingReceiptId: "rcpt-004",
    receiptNumber: "RCPT-2026-0004",
    invoiceNumber: "INV-2026-0004",
    patientMrn: "MRN-2026-0004",
    patientName: "Oluwaseun Adeleke",
    paymentMethod: "POS",
    billingAmount: 95000,
    glPostedAmount: 95000,
    glTransactionRef: "JV-2026-0041",
    status: "MATCHED",
    varianceAmount: 0,
    transactionDate: "2026-09-27",
  },
  {
    id: "recon-005",
    billingReceiptId: "rcpt-005",
    receiptNumber: "RCPT-2026-0005",
    invoiceNumber: "INV-2026-0005",
    patientMrn: "MRN-2026-0005",
    patientName: "Ngozi Obi",
    paymentMethod: "CASH",
    billingAmount: 12000,
    glPostedAmount: 0,
    status: "UNPOSTED_IN_GL",
    varianceAmount: 12000,
    transactionDate: "2026-09-28",
  },
];
